### ISSUE TITLE
mock up builder workflow

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#10]
best done as a PR for the README.md

**Comment by ldecicco-USGS** [comment]
```
print.gsplot <- function(){

   plot
   calc_views
   draw_grids
   draw_points
   draw_axes
   draw_legend
   box
   title
}
```

Views:
xlim, ylim, sides (can be 2 3 4), ylab, xlab, points (list returned from point call), lines (same), y.ticks, x.ticks

If `sides` specified, you'll get a label (ticks, tick label, label). For now, If not specified flat line.

**Comment by jordansread** [comment]
we'll need to call a function to set defaults probably before calling calc_views()
