### ISSUE TITLE
segments(x0=1, y0=2, 3, 4) fails

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#101]
Error in (function (x0, y0, x1 = x0, y1 = y0, col = par("fg"), lty = par("lty"),  : 
  formal argument "x0" matched by multiple actual arguments

This ends up doing this to the args:

params
$x0
[1] 3

$x0
[1] 1

$y0
[1] 2

$y1
[1] 4

**Comment by ldecicco-USGS** [comment]
Oh, I just fixed the same thing for the error bar functions. I'll get to this at some point (unless someone whats to look at what I did).
