### ISSUE TITLE
why is dev.new only called if dev.cur() != 1?

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#103]
from print.R:

``` R
 if(!(dev.cur() == 1) && !("new" %in% names(gsOptions))){
    plot.new()
  }
```

seems like this should be

``` R
 if((dev.cur() == 1) && !("new" %in% names(gsOptions))){
    plot.new()
  }
```

**Comment by jordansread** [comment]
OK, I think I get it, but this results in a fail when you don't have any plots started.

**Comment by ldecicco-USGS** [comment]
I _think_ I was trying to get the user the ability to set new=TRUE (ie...for insets). Definitely not well tested....but generally was working OK for me.

**Comment by ldecicco-USGS** [comment]
dev.XXX functions are poorly documented if you ask me.
