### ISSUE TITLE
multi-gsplots don't work with layout()

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#109]
guessing it has something to do w/ https://github.com/USGS-R/gsplot/blob/master/R/print.R#L24

**Comment by jordansread** [comment]
see @lindsaycarr 's example on #94

**Comment by jordansread** [comment]
``` R
layout(c(1,2,3,4))
plot(1,2)
dev.cur()
[1] 2
```

which is why we don't get a plot.new() when we use layout.

**Comment by jordansread** [comment]
played around with this for too long. setting to wontfix and we should just push people to use split.screen(). Not sure if par(mfcol=2) works or not.

**Comment by ldecicco-USGS** [comment]
I think jumping to 'won't fix' is a bit of a rash decision....is there a 'table issue for now' option. In an ideal world this works.

**Comment by thongsav-usgs** [comment]
This will likely be an immediate impact on repgen's UV hydrographs, which currently uses layout and has N plots.

**Comment by lindsayplatt** [comment]
I can spend some time working on this @jread-usgs

**Comment by lindsayplatt** [comment]
The same thing happens with split.screen, so the issue must be somewhere else. 

``` r
split.screen(figs = c(2,1))
dev.cur()
```

**Comment by jordansread** [comment]
@ldecicco-USGS `wontfix` for right now, because we can use split.screen(). I will create a longer term label. Just didn't want to dwell on this because split.screen will serve near-term issues.

@lindsaycarr  doesn't 

``` R
split.screen(c(1,2))
gs
gs
```

work for you?

**Comment by ldecicco-USGS** [comment]
This works now:

``` r
library(RColorBrewer)
num.plots <- 4
ncol <- 2
nrow <- 2
plotmatrix <- matrix(seq(1:num.plots), ncol, nrow) 
colors <- brewer.pal(length(plotmatrix), "Reds")

png("test.png")
layout(plotmatrix)
for(i in 1:num.plots){
  gs<-gsplot() %>%
    points(i,2,col=colors[i],pch=19,cex=2) 
  print(gs)
}
dev.off()
```

![test](https://cloud.githubusercontent.com/assets/1105215/8830646/f6f80816-3062-11e5-891e-f215332dde65.png)

**Comment by aappling-usgs** [comment]
This seems to be a problem again...

@ldecicco-USGS's example above doesn't work for me:

``` r
library(RColorBrewer)
num.plots <- 4
ncol <- 2
nrow <- 2
plotmatrix <- matrix(seq(1:num.plots), ncol, nrow) 
colors <- brewer.pal(length(plotmatrix), "Reds")

png("test.png")
layout(plotmatrix)
for(i in 1:num.plots){
  gs<-gsplot() %>%
    points(i,2,col=colors[i],pch=19,cex=2) 
  print(gs)
}
dev.off()
```

![test](https://cloud.githubusercontent.com/assets/12039957/10315212/85423438-6c1e-11e5-98f9-48f14d901b70.png)

and @lindsaycarr came up with another simple example that illustrates the problem:

Base R works:

``` r
nf <- layout(matrix(c(1,2,3,4), 4, 1, byrow=TRUE))
plot(1,2)
plot(3,4)
plot(5,6)
plot(7,8)
```

![image](https://cloud.githubusercontent.com/assets/12039957/10315228/a922291c-6c1e-11e5-9adc-73300c2cbca7.png)

But gsplot doesn't:

``` r
gs1 <- gsplot() %>% points(1,2)
gs2 <- gsplot() %>% points(3,4)
gs3 <- gsplot() %>% points(5,6)
gs4 <- gsplot() %>% points(7,8)
nf <- layout(matrix(c(1,2,3,4), 4, 1, byrow=TRUE))
gs1
gs2
gs3
gs4
```

![image](https://cloud.githubusercontent.com/assets/12039957/10315237/b2c25140-6c1e-11e5-8c93-e8b7d15fd30d.png)

**Comment by ldecicco-USGS** [comment]
I'm almost positive it's:
https://github.com/USGS-R/gsplot/blob/master/R/print.R#L45

Let me poke around and see what needs to happen.

**Comment by jordansread** [comment]
I am nasty :( https://github.com/USGS-R/gsplot/commit/cc24c0bcafad4b808fa6595753771206fc2fc410

**Comment by jordansread** [comment]
this is in the readme too, not sure why I didn't catch it w/ re-knit

**Comment by ldecicco-USGS** [comment]
So I commented that line out, and checks passed, the vignette look fine, readme looks fine. 

@jread-usgs ...any idea why that was in there? As long as I'm in `gsplot` world, I'll do a few other issues that have been bugging me before a PR.

**Comment by ldecicco-USGS** [comment]
Looks like it might be taking care of #248 too

**Comment by ldecicco-USGS** [comment]
I lied, I need to do some other work, so I think the little PR I just submitted is all I can get to today. If anyone has a good reason not to merge, let me know.
