### ISSUE TITLE
where do par arguments go? 

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#113]
``` R
gsplot(mar=c(4,4,4,4)) %>% ...
```

**Comment by jiwalker-usgs** [comment]
I like that, also maybe having a function that can be sprinkled in the workflow (maybe `config(mar=c(4,4,4,4))` )?

**Comment by jordansread** [comment]
yes, I think we need both!

**Comment by ldecicco-USGS** [comment]
#14 shows how I thought we were doing it...I'd prefer what you have above (or both). Also, #14 use to work...now I get some error. I'll do more troubleshooting later.

**Comment by jordansread** [comment]
ok, I didn't catch that, so I probably broke something that you were leaning on there. Am trying (in general) to cut down on code lately...but still trying to support these must-haves.

**Comment by jordansread** [comment]
@jiwalker-usgs any reason that `config` shouldn't be `par` for your code above?

**Comment by jiwalker-usgs** [comment]
Only that we might want to allow more options than par supports and feed them accordingly to par or whatnot.  I'm thinking of higher level stuff and future options we might want to allow.  Also, not sold on config as the name.

**Comment by jordansread** [comment]
cool. Would still be nice to wrap par as par(gsplot, ...) and stick that into config appropriately too.

**Comment by ldecicco-USGS** [comment]
I'd be up for a meeting (sprint?) for 1-3 hours or so to re-familiarize everyone with what's going on and see if we need to focus some re-factor jobs somewhere.

**Comment by jordansread** [comment]
@ldecicco-USGS awesome idea. Let's coord w/ @jiwalker-usgs @lindsaycarr @mhines-usgs me and you when you get back. Hope FL is going well.

**Comment by ldecicco-USGS** [comment]
Yeah, something got broke...

**Comment by ldecicco-USGS** [comment]
``` r
#More global:
par(mfcol=c(2,2))
for(i in 1:num.plots){
  gs<-gsplot(mar=c(4,4,4,4)) %>%
    points(i,2) 
  print(gs)
}
```

So, just defining par is OK. Want to also be able to add par arguments to the gsplot call. Anything that is not a formal par argument, add warning and ignore (for now).
