### ISSUE TITLE
mtext only allows text to be placed on 'side=1'

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#117]
Example that is working:

``` r
gs <- gsplot()
gsNew <- points(gs, y=1, x=2, col="blue", pch=18, legend.name="Points")
gsNew <- lines(gsNew, c(3,4,3), c(2,4,6), legend.name="Lines", ylab="Data!")
gsNew <- text(gsNew, x=3.5, y=1.5, labels="Test")
gsNew <- abline(gsNew, b=1, a=0, legend.name="1:1")
gsNew <- legend(gsNew, "topleft",title="Awesome!")
gsNew <- title(gsNew, main="Great Graph")
gsNew <- mtext(gsNew, text="More Stuff", side=1, line=2)
gsNew
```

When you change to `side=2` , an error comes up for 'plot.window'.

``` r
 Error in plot.window(xlim = view$gs.config$xlim, ylim = view$gs.config$ylim,  : 
  need finite 'xlim' values 
```

**Comment by lindsayplatt** [comment]
I tried putting a breakpoint at line 39 in print.R -- the value of `view$gs.config$xlim` is the same for `side=1` and `side=2`, but `side=2` produces warnings. 

``` r
view$gs.config$xlim
[1] 2 4
```

``` r
view$gs.config$xlim
[1] 2 4
Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf
```

**Comment by jordansread** [comment]
@lindsaycarr thanks for pointing this out - I will take a look

**Comment by jordansread** [comment]
tricky...

`side` is a real arg for `mtext` (same w/ axis), but we use it as a `gsplot`-specific arg for the other functions. The way this is treated in gsplot is to kick mtext into a different view than the other functions that are (by default) assigning `side=c(1,2)`. 

I don't have a quick fix for it, but maybe we can talk about strategy in our planning/review meeting.

**Comment by jordansread** [comment]
@jiwalker-usgs can this kind of thing be handled by making our `gs.config` arg `sides` instead of `side`? We actually do require it to contain plural values.

**Comment by jiwalker-usgs** [comment]
I actually like keeping it side so it isn't too confusing (referring to the same thing really) and add special handling for it (side is something we should always catch and then pass along to the lower function the modified side (i.e. 5=1, 8=4)

**Comment by ldecicco-USGS** [comment]
me too!

**Comment by jiwalker-usgs** [comment]
@ldecicco-USGS :penguin: :dancer:

**Comment by jordansread** [comment]
ok, cool :dancers: 

side point (ha! bad dad joke!), but I realized that lindsay's example is actually assigning side = c(2,1) to mtext, so I need to fix that and see if this is still a bug.

**Comment by jordansread** [comment]
got a PR coming for this, but now:

``` R
gs <- gsplot()
gsNew <- points(gs, y=1, x=2, col="blue", pch=18, legend.name="Points")
gsNew <- mtext(gsNew, text="More Stuff", side=2, line=2)
gsNew
```

does this: 

![image](https://cloud.githubusercontent.com/assets/2349007/8732408/e3353cc6-2bc2-11e5-93be-d561b9988cec.png)

**Comment by lindsayplatt** [comment]
:+1:
