### ISSUE TITLE
Axis got broke somehow

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#122]
I _know_ this worked, because I spent a lot of time making it work:

``` r
gs <- gsplot() %>%
   points(x=1:5, y=1:5, legend.name="Stuff") %>%
    lines(2:6, y=2:6, ylim=c(0,10)) %>%
    axis(side=c(3,4),labels=FALSE) %>%
    legend("topright")
gs
```

I think this is an important feature...so I'm going to remove the \dontrun, meaning the checks won't pass until we fix it.

**Comment by lindsayplatt** [comment]
This example produces the same error that occurred with changing side from `side=c(1,2)` to `side=c(3,4)` in mtext, #117

**Comment by ldecicco-USGS** [comment]
Yeah, all the logic that allowed axis sides to be defined without corresponding data is gone now I think. I'll try to dig up a link with the deleted logic...maybe you can sneak it back in.

**Comment by ldecicco-USGS** [comment]
Same as #127
