### ISSUE TITLE
Handle no data situation? in the get

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/gsplot#124]
e.g. if we pass in an an empty dataset to gsplot, handle that situation so it doesn't fail.

**Comment by jordansread** [comment]
we might not want to handle NULL or missing, but we want to handle NA

**Comment by ldecicco-USGS** [comment]
I agree in #53

**Comment by lindsayplatt** [comment]
Issue with handling lines with NA and then lines with date values:

``` r
dates <- seq(as.Date("1970-01-01"), as.Date("1970-01-31"), by="days")
y_vals <- runif(length(dates), min=0, max=100)

par(mfcol=c(2,1))
gs <- gsplot() %>% lines(NA, NA, xlab="DATES", ylab="VALUES", log='y') %>% points(dates, y_vals) 
gs

gsNO <- gsplot() %>% points(dates, y_vals) %>% lines(NA, NA, xlab="DATES", ylab="VALUES", log='y')
gsNO
```

**Comment by ldecicco-USGS** [comment]
Is this OK? There's a warning, but still plots the empty plot. @lindsaycarr  or @jread-usgs close or comment on what you'd like to see.

**Comment by jordansread** [comment]
I think we need a better warning or no warning to close this issue. Either the warning should provide more info (if we want to warn in this case) or the warning shouldn't exist here. That is my $0.02

**Comment by lindsayplatt** [comment]
For the example above, the x tick labels default to the first set of data plotted, even if it is NA. I think we should keep a warning (but definitely add our own) so that people have an easier time understanding why their labels are like that.

**Comment by ldecicco-USGS** [comment]
@lindsaycarr I'm not sure I follow what you are saying. I think the warnings should make more sense, but the labels look fine to me.

Now, if you do all NA's with log="y", that cause a pretty big limit problem. I'll try to catch that in #223

**Comment by lindsayplatt** [comment]
NA's before dates gives tick mark labels as integers:

``` r
gs <- gsplot() %>% 
     lines(NA, NA, xlab="DATES", ylab="VALUES", log='y') %>% 
     points(dates, y_vals) 
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/9919886/3ff15fb4-5c95-11e5-8cfb-c60690b40594.png)

NA's after dates give tick mark labels as dates:

``` r
gsNO <- gsplot() %>% 
     points(dates, y_vals) %>% 
     lines(NA, NA, xlab="DATES", ylab="VALUES", log='y')
gsNO
```

![image](https://cloud.githubusercontent.com/assets/13220910/9919905/6aaff792-5c95-11e5-90a8-26cb3aebdcc1.png)

Shouldn't a NA values not impact the limits, tick labels, etc?

**Comment by ldecicco-USGS** [comment]
Ah, OK that makes sense. In this case, it's getting mixed types in a single axis (NA's are numeric and Dates are Dates...unless it starts off with Dates, then it thinks all the NA's are NA dates). 

We could make another warning that there are mixed types in the same axis.

That being said....I kind of feel like this is _such_ a weird case, we should work on making clear warnings, and not waste too much time changing the overall logic. Hopefully, people don't throw NA entries on purpose, so if they do it accidentally, the warnings should clue them into something weird's going down. 

We can also improve our documentation to make sure people understand how to do log scales without this hack. I'd love to see our documentation cleaner and more informative than base R.

**Comment by lindsayplatt** [comment]
Ah ok, this is a very specific case, but I definitely agree we should have more informative documentation and maybe even warning/error messages than base R

**Comment by jordansread** [comment]
This is no longer an issue w/ #317

``` r
dates <- seq(as.Date("1970-01-01"), as.Date("1970-01-31"), by="days")
y_vals <- runif(length(dates), min=0, max=100)

par(mfcol=c(2,1))
gs <- gsplot() %>% lines(NA, NA, xlab="DATES", ylab="VALUES", log='y') %>% points(dates, y_vals) 
gs

gsNO <- gsplot() %>% points(dates, y_vals) %>% lines(NA, NA, xlab="DATES", ylab="VALUES", log='y')
gsNO
```

![image](https://cloud.githubusercontent.com/assets/2349007/14583065/4967a92e-03dc-11e6-9e66-e716677e0fdc.png)
