### ISSUE TITLE
support date types 

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#125]
`graphics`:

``` R
plot(as.Date('1970-01-01'), 4)
```

![image](https://cloud.githubusercontent.com/assets/2349007/8755293/72503826-2c8f-11e5-875c-66c59e15de77.png)
`gsplot`:

``` R
gs = gsplot() %>% points(as.Date('1970-01-01'), 4)
gs
```

![image](https://cloud.githubusercontent.com/assets/2349007/8755312/8b1d2134-2c8f-11e5-9e93-ee2ee4ddc351.png)

**Comment by lindsayplatt** [comment]
I haven't found a solution, but I think I have been able to determine why gsplot can't handle dates and base plot can. In `calc_views.R`, the function `summarize_args` changes the data type to numeric (the function is called in line 124). Then, this is used to set the x-axis limits in `set_view_lim`, but the x-values are no longer dates. 

https://github.com/USGS-R/gsplot/blob/master/R/calc_views.R#L142-L152

**Comment by ldecicco-USGS** [comment]
Good sleuthing. Let's discuss this afternoon.
