### ISSUE TITLE
Side info goes missing

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#126]
``` r
usrDef <- gsplot() %>% 
 points(x=1, y=2, side=c(3,2), legend.name="Points 1", cex=3) %>% 
 points(x=3, y=4, side=c(1,4), legend.name="Points 2", pch=5, col="red") %>% 
 lines(x=c(3,4,3), y=c(2,4,6), legend.name="Lines 1", lty=5, col="orange") %>%
 lines(x=c(1,2,5), y=c(1,8,5), legend.name="Lines 2", lwd=3) %>%  
 legend(x=1.5,y=4)
usrDef
```

**Comment by jordansread** [comment]
just trying to make sure I understand this right:

The two `lines` calls will end up w/ `side=c(1,2)` (which they do) and then we should end up with the two `lines` and the second points call defining limits of side[1]. side[3] will be c(0.5,1.5), and side[2] should be made up of both `lines` calls and the first `points` call. 

I think there will be three views, and we can probably expect overplotting of axis 1 and 2 (given they will appear in 2 views each), but the ticks and limits should line up for those.

**Comment by jordansread** [comment]
This is only on my fork right now, but: 

``` R
usrDef <- gsplot() %>% 
     points(x=1, y=2, side=c(3,2), legend.name="Points 1", cex=3, xlab='cat') %>% 
     points(x=3, y=4, side=c(1,4), legend.name="Points 2", pch=5, col="red") %>% 
     lines(x=c(3,4,3), y=c(2,4,6), legend.name="Lines 1", lty=5, col="orange") %>%
     lines(x=c(1,2,5), y=c(1,8,5), legend.name="Lines 2", lwd=3, ylab='dog') %>%  
     legend(x=1.5,y=4)
usrDef
```

![image](https://cloud.githubusercontent.com/assets/2349007/8816529/c0f8ecb4-2fed-11e5-96b8-afba404b3105.png)

**Comment by jordansread** [comment]
Am totally up for rethinking the views list structure to make it easier to work with...

**Comment by ldecicco-USGS** [comment]
That's how I would assume it should work (this was just a very convoluted examples). As for rethinking the list structure...am totally for a discussion.

**Comment by ldecicco-USGS** [comment]
So moving that par to after plot window seems to screw this up again. I'll move it back.

**Comment by jordansread** [comment]
I think we can close this. Re-open if this pops up again. I will add something to the readme knit so this is obvious if if pops up.
