### ISSUE TITLE
Configurable date handling

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#134]

**Comment by ldecicco-USGS** [comment]
Example, we might create a custom date handling function to get SPN functionality. Then, we could add these arguments in the config.

**Comment by lindsayplatt** [comment]
Fairly complex because it needs to use limits to calculate correct tick and label positions, but limits change as new data is added to the object.

Easy implementation/bandaid - special axis function. 
Fancier - use lazyEval stuff on print

date/posix class triggers special recalculation of limits from regular axis call
Should be able to do this without the theme, but can specify this in theme

**Comment by lindsayplatt** [comment]
Two axis calls - one for labels, one for ticks (using `append=TRUE`)
Need to have an updating "at" (JW)

```r
gs <- gsplot() %>% 
    points(seq(as.Date("2010-10-01"), as.Date("2011-10-01"), by="months"), 1:13) %>% 
    axis(side=1, smartAxis=TRUE)
gs
```

Reference this smwrGraphs doc for possible scenarios: https://github.com/USGS-R/smwrGraphs/blob/master/inst/doc/DateAxisFormats.pdf 

Smart date axis:
- Centering label logic: is diff between ticks constant,
- figures out what the format of label is

labeling ticks or labeling intervals (where ticks are interval boundary)?

water years?!?!?!?!?!?!?

**Comment by lindsayplatt** [comment]
Want it to be more flexible than just having an on/off switch. If trying to capture all date axis formats, this should be a different function. 

Straw dog please @jiwalker-usgs

**Comment by jiwalker-usgs** [comment]
Axis Rules
==========

Limit Calculation
 * when to pick limit
 * what overrides this limit
 * do other rules break down when overridden
Tick positioning
 * minor axis ticks
 * should ticks align with limits?
Label positioning
 * center on instants
 * center on interval 

Proposal
========

add an extra function (lessons from error_bar, etc useful here) axis_labels (labels is taken)
under the covers this will add an additional axis call with the proper rules
allows for new attribute (pos='center') that will center on the intervals
inherits attributes (at, outer, col) from axis on same side (or opposite) if they match
special handling for dates (snap.to=hour, day, week, month, year, wateryear, decade)
this is what modifies the limits, altering where ticks end up

Code Examples
=============

```
x <- seq(as.Date("2013-01-22"), as.Date("2013-12-02"), "days")
y <- rnorm(length(x), 71, 19)
gs <- gsplot() %>%
  points(x, y, ylim=c(0, NA)) %>%
  axis_labels(pos="center", snap.to="year")
gs
```

ends up like

```{r}
x <- seq(as.Date("2013-01-22"), as.Date("2013-12-02"), "days")
y <- rnorm(length(x), 71, 19)
year <- c(as.Date("2013-01-01"), as.Date("2013-12-31"))
gs <- gsplot() %>%
  points(x, y, ylim=c(0, NA), xlim=year) %>%
  axis(side=1, at=seq(year[1], year[2], "months"), labels=FALSE) %>%
  axis(side=1, at=seq(year[1], year[2], "months")+15, tick=FALSE, append=TRUE)
gs
```

**Comment by lindsayplatt** [comment]
- Is this function only for dates, or is it for factors? Just dates.
- This function will take the place of any `axis` call - it can handle all axis args. Therefore, it needs a different name. `dateAxis` or something.
- water years??

**Comment by jiwalker-usgs** [comment]
I'm going to close this unless we know of anything that is missing.  We probably want to try out some of the new theme work to make sure date handling works appropriately.
