### ISSUE TITLE
Formulas should be allowed

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#146]
``` r
plot(-3:3,-3:3)
points(y~x)

library(gsplot)
gs <- gsplot() %>%
  points(y~x)
gs
```

**Comment by jordansread** [comment]
see #151

**Comment by ldecicco-USGS** [comment]
I think this is going to be a little trickier...not 100% sure. Have to make sure plot calls plot.formula appropriately. Also, plot.factor? plot.ts? plot.data.frame? plot.function?

**Comment by jordansread** [comment]
I linked in the wrong issue for that last comment. I have not worked on this issue. Agree that it will be tricky.

**Comment by jordansread** [comment]
I think we need something like this when we look up the function, and then failover to `.default`:

``` R
getS3method('points',class(object), optional=TRUE)
```

which works for class(object) == 'formula'

**Comment by jordansread** [comment]
- [x] support for base plot override (i.e., what LDC has above breaks when `gsplot` is loaded
- [x] support for using formulas in gsplot workflow (the second example from LDC)

**Comment by jordansread** [comment]
see #159 which takes care of the first thing.

**Comment by jordansread** [comment]
Is this still open? 

What is the criteria for closing? 

this works

``` R
gs <- gsplot() %>%
    points(y~x, data=list(x=-3:3,y=-3:3))
gs
```

what other patterns do we have? ones that look to the parent.frame for x and y as well?

**Comment by ldecicco-USGS** [comment]
I didn't check, but does it work for lines too? That was the one thing I was going to check before closing.

**Comment by jordansread** [comment]
yep, it does
