### ISSUE TITLE
order_views function drops things that aren't legends or views

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#149]
we need to be able to send a `views` list into order_views and not have it drop elements. 

If I send this in:
![image](https://cloud.githubusercontent.com/assets/2349007/8842051/0f332c82-30bb-11e5-8331-e9f50f59acaf.png)

I get this back:
![image](https://cloud.githubusercontent.com/assets/2349007/8842059/209f239a-30bb-11e5-892f-83ccd6bc19ac.png)
(I lost par() and got an empty `view` in its place)

**Comment by ldecicco-USGS** [comment]
Where's order_views?

**Comment by jordansread** [comment]
it is here https://github.com/USGS-R/gsplot/blob/master/R/calc_views.R#L21

but I pulled it out into a function and didn't change the code.
