### ISSUE TITLE
need a is.gsplot() or something similar for gsplot class

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#157]
would make testing etc easier. For example, gsplot can have any number of `points` or `lines` etc fields, but it should only have one `par` field. 

other checks could be put in here too.

**Comment by ldecicco-USGS** [comment]
Expand `is.gsplot` (and I suppose create) to not just check the class but also if it's valid.

**Comment by lindsayplatt** [comment]
What other checks will need to be in this function? I currently have it set up to check `class(object) == "gsplot"` and that there is only one `par`.

However, I cannot find a scenario where multiple `par` arguments will be in the object list. When I have added more `par()` statements, they are put under the same list argument:

``` r
usrDef <- gsplot() %>% 
    points(x=1, y=2, side=c(3,2), legend.name="Points 1", cex=3) %>% 
    points(x=3, y=4, side=c(1,4), legend.name="Points 2", pch=5, col="red") %>% 
    lines(x=c(3,4,3), y=c(2,4,6), legend.name="Lines 1", lty=5, col="orange") %>%
    lines(x=c(1,2,5), y=c(1,8,5), legend.name="Lines 2", lwd=3) %>%  
    lines(x=c(2,4), y=c(3,6), legend.name="Lines 3", lty=2, col="blue") %>%
    par(mfcol=c(2,1)) %>%
    par(las=2) %>%
    legend(x=1.5,y=4)
usrDef
```

**Comment by lindsayplatt** [comment]
Additionally, should the function be internal (part of `print`) and halt plot execution? Current commit/PR just outputs vector saying "Valid" or "Invalid" for each check

**Comment by ldecicco-USGS** [comment]
Definitely not internal. It is considered very good practice to have a validation function available.

**Comment by lindsayplatt** [comment]
So this would just be for a user to check?

**Comment by ldecicco-USGS** [comment]
A user or in the package...whereever

**Comment by lindsayplatt** [comment]
Oh ok, I guess by internal I was thinking more along the lines of automated - somewhere the package would run this and if something was invalid, it would produce an error?

**Comment by ldecicco-USGS** [comment]
I'm really not sure on how we are going to handle `par`. I can think of many situations where I actually would want multiple `pars`.....so we'll have to think about `par` in another conversation. As for other validity tests...we'll just have to start thinking about what's valid/not (maybe get inspiration in the tests). It shouldn't be too big of a function though. For now `class(object) == "gsplot"` is fine.

**Comment by lindsayplatt** [comment]
Ok, so the PR I just submitted has a # of par arguments check. Should I close that PR, make the changes, and resubmit the PR?

**Comment by ldecicco-USGS** [comment]
That would be my vote. Literally the whole function should be `return(class(object) == "gsplot")`

As we discover things the users could screw up - that we can't programmaticly fix, we can add it.

**Comment by lindsayplatt** [comment]
Ok, wow...I've severely over-coded here.

**Comment by ldecicco-USGS** [comment]
Nah, fully addresses. If validations need to be added later, we open a new issue.

**Comment by lindsayplatt** [comment]
@ldecicco-USGS  :+1:
