### ISSUE TITLE
plot(x) 

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#165]
I forget if we decided to ignore this or what. Anyway, in base R:

``` r
plot(1:10)
```

Whereas:

``` r
gs <- gsplot() %>%
     points(1:10)
gs

Warning message:
In is.na(data.var) : is.na() applied to non-(list or vector) of type 'NULL'
```

**Comment by jordansread** [comment]
another tricky one. points (and plot) call `xy.coords` internally, which turns `x=5:7` and `y=NULL` into `x=1:3` and `y=5:7`. We would need to have that happen, _then_ grab the coords for our limit calculations. I think we should do that (or something simpler if possible), but I looked into it briefly and didn't see a very clean way to do it.
