### ISSUE TITLE
x-axis error_bar produces strange warnings and plots

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#176]
When defining the x.high and x.low values, the following warning message is produced: `zero-length arrow is of indeterminate angle and so skipped`. Also, defining all 4 values (x low/high and y low/high) produces strange angled bars (see examples below).

``` r
gs <- gsplot() %>%
    points(1:10, 1:10) %>%
    error_bar(5, 5, x.high=1)   #x.low=1 doesn't work, but y.low=1 and y.high=2 do work  
gs 

#produces 
Warning message:
In (function (x0, y0, x1 = x0, y1 = y0, length = 0.25, angle = 30,  :
  zero-length arrow is of indeterminate angle and so skipped
```

Additionally, defining all 4 resulted in a strange angled x.low error_bar:

``` r
gs <- gsplot() %>%
    points(1:10, 1:10) %>%
    error_bar(5, 5, x.high=1, x.low=2, y.high=1, y.low=1) 
gs 
```

![image](https://cloud.githubusercontent.com/assets/13220910/9065871/e58a6dc6-3a99-11e5-9721-9895f1a680fd.png)

**Comment by ldecicco-USGS** [comment]
I think that's fixed with the current pull request. There's a lingering axis issue in there I still am getting to, but I think it's basically good to go, I'll merge it now. Grab those changes and see if that helps.

**Comment by lindsayplatt** [comment]
Oh yes -- that did!
