### ISSUE TITLE
Would like to specify xaxt='n'

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/gsplot#178]
We (me and @lindsaycarr) are running into an issue with overplotting axis. It seems like in plot we can tell something to not put out an axis by default with xaxt='n', but we cannot achieve that with gsplot.

Here is an example for how gsplot handles it:

``` r
xdata <- seq.Date(as.Date("2010-10-01"), as.Date("2010-10-31"), by="days")
ydata <- runif(length(xdata), 0, 50)

gs <- gsplot() %>%
 points(x=xdata, y=ydata, type='l') %>%
 axis(side=c(1,2), at=xdata, labels=as.character(1:length(xdata)))
gs
```

Here is how plot handles it with xaxt:

``` r
plot(xdata, ydata)
axis(side=1, at=xdata, labels=as.character(1:length(xdata)))

plot(xdata, ydata, xaxt='n')
axis(side=1, at=xdata, labels=as.character(1:length(xdata)))
```

We would like to be able to:

```
gs <- gsplot() %>%
 points(x=xdata, y=ydata, type='l' xaxt='n') %>%
 axis(side=c(1,2), at=xdata, labels=as.character(1:length(xdata)))
gs
```

**Comment by jiwalker-usgs** [comment]
I would think that xaxt should always be 'n' on the underlying points call.  If the user explicitly calls xaxt, then we should withhold the underlying axis call so as to avoid drawing the axis altogether.  I think some of our implicit dealings (axis and legend) force us to deal with some par arguments differently.

**Comment by ldecicco-USGS** [comment]
Exactly what I was saying here:

#171

**Comment by ldecicco-USGS** [comment]
With the PR I did the other day, you can turn off axes, then rebuild:

``` r
xdata <- seq.Date(as.Date("2010-10-01"), as.Date("2010-10-31"), by="days")
ydata <- runif(length(xdata), 0, 50)

gs <- gsplot() %>%
 points(x=xdata, y=ydata, type='l', axes=FALSE) %>%
 axis(side=1, at=xdata, labels=as.character(1:length(xdata)))%>%
 axis(side=2)
gs

```

**Comment by mhines-usgs** [comment]
Ok @ldecicco-USGS, is this redundant then? Should I close it?

**Comment by ldecicco-USGS** [comment]
I'll pull your example in there.
