### ISSUE TITLE
error_bar, callout, axis limits

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#185]
limits need to be incorporated into our smart limits.

**Comment by jordansread** [comment]
Can we get a reproducible example (code + screenshot) of this bug?

**Comment by ldecicco-USGS** [comment]
``` r
gs <- gsplot() %>%
   points(1:10, 1:10) %>%
   error_bar(5, 5, y.high=50) 
gs 
```

**Comment by ldecicco-USGS** [comment]
So I think just moving the logic from error_bar.default to error_bar.gsplot could take care of this. Same with callouts.

**Comment by lindsayplatt** [comment]
What about in the calc_views `set_view_lims` function somewhere? Then we wouldn't have to change to callouts and error_bars, just add a line or two checking for those before defining the limits

**Comment by ldecicco-USGS** [comment]
Either way would work. The question is which function do we want to muck up the most. I like the idea of keeping the calc_view stuff as generalized as possible and leaving all the function specific stuff in the  functions.

**Comment by lindsayplatt** [comment]
Ah ok, good point

**Comment by jordansread** [comment]
I think I know what we are talking about. If so, I think the logic should be in error_bar.gsplot..I think. (and callouts)

**Comment by lindsayplatt** [comment]
This is how the limits automatically look for arrows -- you can't see the horizontal bar ending the line because it is on the axis

![image](https://cloud.githubusercontent.com/assets/13220910/9262214/cb19fa10-41d8-11e5-85c7-049268b9aed6.png)

**Comment by ldecicco-USGS** [comment]
I don't think that's an issue. We butt up points and lines to the tippy top already. An issues is that we should be letting the user pick yaxs and xaxs, but I don't think we are doing this right now.

From `?par`:
The style of axis interval calculation to be used for the x-axis. Possible values are "r", "i", "e", "s", "d". The styles are generally controlled by the range of data or xlim, if given.
Style "r" (regular) first extends the data range by 4 percent at each end and then finds an axis with pretty labels that fits within the extended range.
Style "i" (internal) just finds an axis with pretty labels that fits within the original data range.
Style "s" (standard) finds an axis with pretty labels within which the original data range fits.
Style "e" (extended) is like style "s", except that it is also ensures that there is room for plotting symbols within the bounding box.
Style "d" (direct) specifies that the current axis should be used on subsequent plots.
(Only "r" and "i" styles have been implemented in R.)

**Comment by ldecicco-USGS** [comment]
So putting in yaxs="r" would hopefully add a buffer.

**Comment by lindsayplatt** [comment]
Yep - just changed it in the yaml and that worked!

**Comment by ldecicco-USGS** [comment]
I think yaxes = "r" (and x) makes us lose our smart limits however. So, if you could check that...and if it does break the limits, create a new issue por favor

**Comment by lindsayplatt** [comment]
It doesn't seem to break the smart limits. I just ran:

``` r
gs <- gsplot() %>%
    points(1:3,2:4) %>%
    error_bar(1,2, y.high=0.5, y.low=0.25)
gs
```

Which produced:
![image](https://cloud.githubusercontent.com/assets/13220910/9276016/fcdf03fe-4266-11e5-825a-53d99082d4f4.png)

**Comment by ldecicco-USGS** [comment]
I think it's broken if you specify a limit:

``` r
gs <- gsplot() %>%
    points(1:3,2:4,ylim=c(0,NA) %>%
    error_bar(1,2, y.high=0.5, y.low=0.25)
gs
```

I want to force the y axis to start at zero...but leave it to the omniscient gsplot to figure out the upper....and add a buffer to that.

**Comment by lindsayplatt** [comment]
That works for me - but I had to add parentheses after points:

``` r
gs <- gsplot() %>%
    points(1:3,2:4,ylim=c(0,NA)) %>%
    error_bar(1,2, y.high=0.5, y.low=0.25)
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/9276301/92f2f598-4268-11e5-8385-4ad3b93f8961.png)

**Comment by lindsayplatt** [comment]
The embedded error_points was what I broke before, so I am trying to figure that out this morning

**Comment by ldecicco-USGS** [comment]
No, it's not working because if I specify the ylim, I want it to be exactly what I say (0), if I don't, I want the buffer. So the above should go from 0 to 4.2ish

**Comment by lindsayplatt** [comment]
Ohhhhhhh I see what you are saying now. I'll make a new issue
