### ISSUE TITLE
question about embedding functions within a function

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#188]
see other issue, but I thought I would raise it here as a question:

so the workflow for callouts internally is 

``` r
points(x=1:2, y=3:4, callouts=list(labels=c('point1','point2')))
```

would we consider this?

``` R
points(x=1:2, y=3:4, callouts(labels=c('point1','point2')))
```

which would be possible w/ using `substitute()` within the print method part of the `do.call()`?

**Comment by jordansread** [comment]
if you do this:

``` R
gs <- gsplot() %>% 
    curve(x^2, from=1, to=5, col="blue")
```

from within `curve`, you can capture the arguments in the ellipsis with 

``` R
args = as.list(substitute(list(...)))[-1L]
```

this may also be a way to capture a function call within a function call, and capture and expand its arguments before evaluation. 

you can see if you have any functions in there:

``` R
lapply(args, is.call)
```

**Comment by jordansread** [comment]
tricky thing is that 

``` r
points(x=1:2, y=3:4, callouts(labels=c('point1','point2')))
```

`x=1:2` is a call (while `x=c(1,2)` is not...)

**Comment by jordansread** [comment]
Because we may be dealing with data we should avoid duplicating, I would like to suggest a solution that doesn't expand/copy the embedded data for this pattern. i.e., we don't convert this:

``` R
points(x=1:2, y=3:4, callouts(labels=c('point1','point2')))
```

into this internally:

``` r
points(x=1:2, y=3:4)
callouts(x=1:2, y=3:4, labels=c('point1','point2')))
```

instead, if we can keep the function embedded until the do.call within print (for `points` in this case), we can have the sub function (`callouts` in this case) look up a level for arguments that are missing but necessary. 

Something like that. Copying the data may be easier, but might limit us in the future with really big datasets and multiple embedded calls.

**Comment by ldecicco-USGS** [comment]
@lindsaycarr Could you put some examples in the package in points and lines (and maybe here) showing how this currently is implemented?

**Comment by lindsayplatt** [comment]
The package has some examples:

``` r
# lines
gs <- gsplot() %>%
   lines(x=c(1,2), y=c(4,2), xlim=c(0, 5), ylim=c(0,5),
       callouts=list(labels=c(NA, "data"), col="blue"))
gs

# points
gs <- gsplot() %>% 
         points(x=1:5, y=1:5, xlim=c(0,10), ylim=c(0,10),
               callouts=list(labels=c(rep(NA, 4), "oh")),
               error_bar=list(y.high=1))
gs
```

**Comment by jordansread** [comment]
I think we need `lazyeval` as mentioned by @ldecicco-USGS today. I looked into this, and it is pretty cool.

**Comment by jordansread** [comment]
I think we did this and you can see it with 

``` r
gs <- gsplot() %>% 
    points(x=1:5, y=1:5, xlim=c(0,10), ylim=c(0,10),
           callouts(labels=c(rep(NA, 4), "oh")),
           error_bar(y.high=1))
gs
```

![image](https://cloud.githubusercontent.com/assets/2349007/11608763/2e174bfa-9b38-11e5-980b-056ebc8afcbe.png)
