### ISSUE TITLE
should we be building the plotting object iteratively instead of all at once?

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#193]
curious of views and other things should be built as you add to the gsplot object, or if they should be done all at once as part of `print`. 

breaking it up would help us w/ development debugging. Not sure how I feel on the topic, but since we are talking about modifying the render object structure I thought I would bring this up.

**Comment by jordansread** [comment]
also, one advantage of this is that if we have conflicting things specified in the views, the graceful failover is just to use the most recent setting. So if you had

``` R
gs <- gsplot() %>%
  points(1:2,1:2,xlab='dog') %>%
  lines(3:4, 5:6, xlab='cat')
gs
```

the xlab would be cat. More advantageous for more complicated examples, but you get the point.

**Comment by ldecicco-USGS** [comment]
Interesting...might be helpful to people using it debugging too.

Edit: I can see myself saying..."OHHH that's why the limit's all screwed up"

**Comment by jiwalker-usgs** [comment]
I was thinking about this as well, and I think it is reasonable as long as there isn't too much to deal with as far as maintaining the integrity of the object.  I've been writing this comment for a while and trying to come up with drawbacks, but can't come up with anything specific.  If you want to discuss, I probably have some strong opinions one way or another.

**Comment by jordansread** [comment]
are we doing this?

**Comment by ldecicco-USGS** [comment]
It's my vote.

**Comment by jiwalker-usgs** [comment]
I think I'm convinced.

**Comment by jordansread** [comment]
I am trying this

**Comment by jiwalker-usgs** [comment]
:+1:

**Comment by jordansread** [comment]
WIP here: https://github.com/jread-usgs/gsplot/tree/iterative-builder

but I broke legend and I think I broke logged axes when using multiple calls to the same side

**Comment by jordansread** [comment]
that PR is ready for review
