### ISSUE TITLE
plot data with completely different y-axis

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#196]
So, I am not sure if this falls somewhere in our par() discussion but I want to plot water temperature on the left axis and pH on the right axis. In order to do so, you need to call `par(new=TRUE)`. My ideal workflow is to incorporate `side=4` into lines() or points(), but that would divert from base r behavior. 

``` r
dates <- seq(as.Date("1980-10-01"), as.Date("2010-10-01"), by="years")
pH <- runif(length(dates), 0, 14)
Wtemp <- runif(length(dates), 0, 100)

# base plot method
plot(dates, Wtemp, col="royalblue", type='l')
par(new=TRUE)
plot(dates, pH, col="orangered", type='l', axes=FALSE)
axis(side=4)

# what gsplot currently produces
demoPlot <- gsplot() %>% 
  lines(dates, Wtemp, col="royalblue") %>%
  lines(dates, pH, col="orangered") %>%
  axis(side=4, at=pH)
demoPlot

# ideal workflow to get data to plot on y-axis of different values
demoPlot <- gsplot() %>% 
  lines(dates, Wtemp, col="royalblue") %>%
  axis(side=4, at=pH) %>%
  lines(dates, pH, col="orangered", side=4)
demoPlot
```

**Comment by ldecicco-USGS** [comment]
You can do that by defining sides (unless I'm misunderstanding something):

``` r
demoPlot <- gsplot() %>% 
  lines(dates, Wtemp, col="royalblue", side=c(1,2)) %>%
  lines(dates, pH, col="orangered", side=c(1,4)) 
demoPlot
```

**Comment by jiwalker-usgs** [comment]
Should `lines()` be able to handle `side=4` and assume that means `c(1,4)`?

**Comment by ldecicco-USGS** [comment]
We never implemented that, but that has always been my vote.

**Comment by lindsayplatt** [comment]
Yes, this is exactly what I was referring to. I was missing the c(1,4) because I had tried just `side=4` and it didn't work. I vote to implement the ability to just say `side=4` also.

**Comment by ldecicco-USGS** [comment]
Quorum!

**Comment by jordansread** [comment]
indeed!
