### ISSUE TITLE
Argument for legend - > pt.bg

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/gsplot#197]
Even if points are styled with an outline and background (col='black' and bg='yellow') the legend symbol only displays black outline.

``` r
gs <- gsplot() %>%
points(1,2,col='black',bg='yellow',pt.bg='yellow', pch=21, legend.name='test legend item') %>%
legend()
```

**Comment by ldecicco-USGS** [comment]
The bg parameter is actually suppose to be bg of "device region". Maybe we should actually replace the `bgCol` function with a 'overarching' argument bg like we discussed with axes and others:

``` r
gs <- gsplot(axes=FALSE, bg="yellow") %>%
  points(1,2)
```

So, the col argument (black) is being passed on correctly.

**Comment by ldecicco-USGS** [comment]
@lindsaycarr you want to take a crack at this? If you do, there are some other obvious things that could be improved in the legend function. Stop by and we can chat.

**Comment by lindsayplatt** [comment]
@ldecicco-USGS I've got something else I am finishing up today, can we chat tomorrow after standup?

**Comment by ldecicco-USGS** [comment]
Sure
