### ISSUE TITLE
type="b"

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#200]
It's pretty common to want both points and lines. We can do that currently by specifying both...but then the legend gets 2 enteries. @lindsaycarr  and I were talking about a new workflow like this:

``` r
gs <- gsplot() %>%
           points(1:10,1:10, type="b") %>%
           legend()
#or:
gs <- gsplot() %>%
           lines(1:10,1:10, type="b") %>%
           legend()
gs
```

Would look like:

``` r
plot(1:10,1:10,type="b")
legend("topleft", legend = "data", pch=c(21), lty=1)
```

![image](https://cloud.githubusercontent.com/assets/1105215/9254216/e9023ffa-41a7-11e5-9fac-c86866f3aecd.png)

Thoughts?

**Comment by lindsayplatt** [comment]
The only thing that I don't like is that the lines aren't going through the points in the plot, but the legend shows it differently. I would prefer the workflow you suggested to result in 

``` r
gs <- gsplot() %>%
      points(1:10, 1:10, pch=1, col="black", legend.name="data") %>%
      lines(1:10, 1:10, legend.name="data") %>%
      legend()
gs
```

But that's more nitpicky I guess

**Comment by ldecicco-USGS** [comment]
Age ol' question.....how much do we emulate base. Definitely implement the workflow you suggest. Then we can discuss if the type="b" argument in base is something we want in gsplot.

**Comment by ldecicco-USGS** [comment]
I meant more generally supporting the types:

![image](https://cloud.githubusercontent.com/assets/1105215/9259603/cd8ba502-41c7-11e5-8064-e331c1473f68.png)

So type="o" is what you are describing.

**Comment by lindsayplatt** [comment]
Oh ok, I didn't even know that they were separate items.

**Comment by jordansread** [comment]
on current version (0.3.0):
![image](https://cloud.githubusercontent.com/assets/2349007/9767139/4de5b5b0-56e2-11e5-927a-3d4bd8ef5cd2.png)

``` R
gs <- gsplot() %>%
    lines(1:10,1:10, type="b", legend.name='sf') %>%
    legend()
gs
```
