### ISSUE TITLE
"get the facts" function -- find details of gsplot object

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#206]
Be able to look at gsplot elements mid-plotting -- I want to know how many lines/points calls there are, or what the par() limits are. 

@jread-usgs and @mhines-usgs can expand on this as well

**Comment by ldecicco-USGS** [comment]
``` r
summary.gsplot
```

**Comment by jiwalker-usgs** [comment]
:+1: this also corresponds with doing the calc_views stuff stepwise https://github.com/USGS-R/gsplot/issues/193

**Comment by ldecicco-USGS** [comment]
Was going to say if we did #193 right, we might not need a separate function...but having a summary method for the gsplot class would make people happy.

**Comment by jordansread** [comment]
yes, this is another argument for doing the iterative gsplot builder. Are we going ahead with that?

**Comment by ldecicco-USGS** [comment]
Not sure exactly what you are talking about. But... like:

xlim.gs
ylim.gs
par.gs

others? 
Or, am I understanding this wrong?

**Comment by lindsayplatt** [comment]
I think it was more like the comment you had above w/ `summary.gsplot`. Since this builds iteratively now, you could run that call and get details of the features that have already been added.

**Comment by ldecicco-USGS** [comment]
Maybe summary.gsplot has simple output of:

summary.gsplot(gs)$par
summary.gsplot(gs)$xlim
summary.gsplot(gs)$ylim

what else?

**Comment by jordansread** [comment]
is that summary, or is `par(gsplot)` the thing you would use to get `par`?

**Comment by jordansread** [comment]
I was thinking summary was just a print method that gives you a truncated idea of what is in `gsplot`, w/o all of the really long data prints

**Comment by lindsayplatt** [comment]
If you set it up that way, will you get to see what the limits are set as? I thought window is in a view not in the gsplot object

**Comment by ldecicco-USGS** [comment]
Yeah, that's what summary usually does. So, this Issue is strictly to get a summary method for gsplot. Cool, I'll make a new issue to get utility functions to easily pull out limits, pars, and whatever else you guys can think of.

**Comment by jordansread** [comment]
:+1:
