### ISSUE TITLE
allow reordering of gsplot list items

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#207]

**Comment by ldecicco-USGS** [comment]
Can you give an example, like how you'd like to see it done?

**Comment by jordansread** [comment]
I would think we should allow 1) reshuffling of the functions in each view, and 2) reshuffling of the view render order..others?

**Comment by lindsayplatt** [comment]
Would we need that to be a specific gsplot ability? Because I have been doing that for AQCU after the gsplot object was created.

**Comment by lindsayplatt** [comment]
- lowest usability, easiest implementation: passing in `where =` into the `after` argument in append `append(x, values, after = length(x))`
- where="last", but could change to "first"
- highest usability, hardest implementation: `z.index` changes order on render (1 = first rendered)
- use `reorder` function and assign id's and use those to reorder (default ids - `lines1`, `lines2`, etc). ids copied into auto legend. `reorder` is an extension to gsplot

ids (superuser) + where (simplest use case)

**Comment by jordansread** [comment]
@lindsaycarr here is what I have so far:

``` r
gsplot() %>% points(1,2, cex=3.5, pch=0, lwd=3) %>% 
   points(1,2, pch=17, col='green', cex=4)
```

![image](https://cloud.githubusercontent.com/assets/2349007/16602309/afd8531c-42d8-11e6-9743-c5dc4c580170.png)

``` r
gsplot() %>% points(1,2, cex=3.5, pch=0, lwd=3) %>% 
   points(1,2, pch=17, col='green', cex=4, where='first')
```

![image](https://cloud.githubusercontent.com/assets/2349007/16602316/baa44224-42d8-11e6-9bb1-412d9826a128.png)

**Comment by lindsayplatt** [comment]
Simple implementation is complete. Closing this issue and can revisit the z.index idea if it becomes a desired feature.
