### ISSUE TITLE
arrows are ignored in calc_views?

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/gsplot#210]
Seeing this in plot (check out the right side)

![image](https://cloud.githubusercontent.com/assets/6920344/9362087/424c4f22-4664-11e5-9556-62166e1bf7ba.png)

(may change to callouts but just letting you know)

**Comment by lindsayplatt** [comment]
@mhines-usgs I think we have decided that arrows and callouts will not be calculated into the limits through gsplot since they aren't representing data. However, we will be coding in an argument "auto" so that the angle of the callout lines change if they are going off of the plot (see issue #212)

**Comment by lindsayplatt** [comment]
Quoting @ldecicco-USGS "Arrows is a base R function and should act like one." 

Therefore, we will have to make sure they aren't cut off within the repgen stuff. Base R graphics does not take arrows into it's limits calculation, so neither are we:

``` r
plot(1,2)
arrows(1,2,5,5)
```

**Comment by ldecicco-USGS** [comment]
Although, to be fair, nothing past the `plot` function is included in base R's limit calculations...hence `gsplot`

**Comment by lindsayplatt** [comment]
...wait really? Why have I not known that fact? I feel silly
