### ISSUE TITLE
make callouts have angle='auto' for the default

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#212]
should be 30 degrees unless callout segment will go outside of plotting area, then use best angle selection (give 4 options around the callout location)

**Comment by lindsayplatt** [comment]
also for arrows?

**Comment by ldecicco-USGS** [comment]
Nope. Arrows is a base R function and should act like one.

**Comment by lindsayplatt** [comment]
:+1: gotcha

**Comment by lindsayplatt** [comment]
Fixed by #218
