### ISSUE TITLE
density not working for legend

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#219]
When any densities are specified to go on the legend (in `polygon` or `rect`), the vector for density is filled with `NA` for points that are not associated with that spec (as is the convention for all legend elements now). However, when `density = NA` it defaults to color filling with the default color (black). Any legend items that are not supposed to show density (aka shading lines) should get the value "NULL".  

``` r
gs <- gsplot()  %>% 
    points(1:2,7:8, legend.name="point")  %>% 
    polygon(x=c(1,3,5), y=c(1,4,1), density=15, 
            col="blue", legend.name="triangle")  %>% 
    legend()
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/9526268/f67de5f6-4cad-11e5-9039-5848032705e1.png)

**Comment by jordansread** [comment]
should missing values be filled with the defaults?

``` R
formals(graphics::legend)
```

**Comment by lindsayplatt** [comment]
Yes, but I couldn't get NULL to be assigned, which is what is needed for density

**Comment by jordansread** [comment]
can you provide the syntax for doing what you want to do w/ `graphics` and then we can go from there? I.e., post it here?

**Comment by lindsayplatt** [comment]
not sure I understand exactly what you are asking

**Comment by jordansread** [comment]
can you share the syntax you want to replicate in `graphics::plot`, so I can see what you are trying to emulate in gsplot?

**Comment by lindsayplatt** [comment]
ah gotcha - I think I was mostly just trying to store all of the legend information as a list (as PT had done before, but using `names(formals(graphics::legend))`. I wasn't trying to replicate anything specific in graphics::plot

**Comment by ldecicco-USGS** [comment]
I think @jread-usgs wants the base-R code for the graph above...but with the correct legend. If this call gets stale, I'll post it

**Comment by jordansread** [comment]
reproducible examples are always helpful when working out these issues :+1:

**Comment by lindsayplatt** [comment]
OHHHH, sorry I'm just having a very slow day. Trying to get the correct legend in base R, but struggling. Wanted to at least give you this.

``` r
plot(1:2,7:8, pch=6, col="red", ylim=c(1,8), xlim=c(1,5))  
polygon(x=c(1,3,5), y=c(1,4,1), 
        density=15, col="blue")  
legend(x="topright", c("points", "polygon"), 
       pch=c(6,NA), density=c(NA,15), 
       col=c("red", "blue"))
```

still has the issue of filling behind the points because density = NA reverts to a fill of par("col")

**Comment by lindsayplatt** [comment]
This gives what I want:

``` r
plot(1:2,7:8, pch=6, col="red", ylim=c(1,8), xlim=c(1,5))  
polygon(x=c(1,3,5), y=c(1,4,1), 
        density=15, col="blue")  
legend(x="topright", c("points", "polygon"), 
       pch=c(6,NA), fill=c("white", "blue"), density=c(NA,15), 
       border=c(NA,par("fg")), col=c("red", NA))
```

![image](https://cloud.githubusercontent.com/assets/13220910/9663279/4b81d244-5229-11e5-93ad-c6ce4fcfc884.png)

**Comment by lindsayplatt** [comment]
``` r
gs <- gsplot()  %>% 
    points(1:2,7:8, legend.name="point")  %>% 
    polygon(x=c(1,3,5), y=c(1,4,1), density=15, 
            col="blue", legend.name="triangle")  %>% 
    legend()
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/10291048/3973fcaa-6b6d-11e5-90d8-ddf2cfbc7469.png)
