### ISSUE TITLE
refactor legend

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#244]

**Comment by jordansread** [comment]
We agree that legend should iteratively build just like the other pieces (`views`) in gsplot.

**Comment by lindsayplatt** [comment]
convert back to list from data frame

**Comment by jordansread** [comment]
Move specific legend arguments to the specific function calls (like `points`). The building of legend should fall under the purview of specific functions

**Comment by jordansread** [comment]
remove `title` as a formal of `legend.gsplot`

**Comment by jordansread** [comment]
remove adjusted margins from legend call (we shouldn't override user's `par()` arguments silently)

**Comment by jordansread** [comment]
we good here?
