### ISSUE TITLE
lost index for points and lines

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#245]
``` R
gs <- gsplot()  %>% 
    points(1:20, col="blue", legend.name="Points 1")  %>% 
    points(20:1, col="green", legend.name="Points 2") %>% 
    legend(location="below")
gs
```

now fails

**Comment by ldecicco-USGS** [comment]
Is this what you are talking about in #224?

**Comment by lindsayplatt** [comment]
Do we need it to have the default labels - e.g. x-axis says "Index", then y-axis says "1:20"? My vote is no.

**Comment by jordansread** [comment]
I think long ago we opted to not have gsplot do that. My vote is no as well.
