### ISSUE TITLE
should using axis(side=...) override tick labels from previous call?

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#260]
When you use `axis()` to make new tick labels, should the original ones not show up? I know `axes=FALSE` exists, but that would also get rid of the y labels - what if I only want to get rid of the x labels?

``` r
gs <- gsplot() %>% 
    points(runif(30, 1,5), runif(30,0.5,3.5), pch=16, col="black", 
           xlim=c(1,5), ylim=c(0.5,3.5)) %>% 
    axis(side=1, at=seq(1,5,by=0.5))
    axis(side=c(3,4), labels=FALSE)
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/10319989/a5f5f2c4-6c36-11e5-8146-c34b42798996.png)

**Comment by ldecicco-USGS** [comment]
Yeah. This was what we were debating ad nauseam. But, we finally decided if you make an axis call, the default should not show up. So, this is now a bug. There's a host of other bugs concerning axis (all pretty much the same-ish problem). I'm going to (maybe today) condense them all into one big issue.

**Comment by lindsayplatt** [comment]
Ok, sounds good. Thanks
