### ISSUE TITLE
Uber-Axis Complaint Thread

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#261]
### ONE.

`axis` call needs to completely override default. axes=FALSE could still be used (?) to turn off all defaults without making new `axis` calls. (#260)

```
gs <- gsplot() %>% 
    points(runif(30, 1,5), runif(30,0.5,3.5)) %>% 
    axis(side=1, at=seq(1,5,by=0.5)) %>%
    axis(side=c(3,4), labels=FALSE)
gs
```

(shouldn't have y axis labels)
### TWO.

If 2 views define the same side, they are over-plotting each other (#248)

```
gs <- gsplot() %>% 
  points(runif(30, 1,5), runif(30,0.5,3.5)) %>%
  points(1:100,1:100,side=c(1,4))
gs
```
### THREE.

limits from axis calls not taken into account (#249)

```
gs <- gsplot() %>%
  points( y=c(3,1,2), x=1:3) %>%
  axis(1, at=1:5)
gs
```
### FOUR.

Conflicting limits need a warning 

```
gs <- gsplot() %>% 
  points(runif(30, 1,5), runif(30,0.5,3.5), 
         xlim=c(1,2), ylim=c(0.5,3.5)) %>% 
  lines(1:10,1:10,xlim=c(1,10))
gs
```
### FIVE.

`axis` call needs to take into account proper `par` calls:

```
 gs <- gsplot() %>%
   lines(1:5, c(1,10,100,1000,10000), log="y") %>%
   axis(side=c(2,4), labels=FALSE, n.minor=4, las=1)
gs
```
### SIX.

`axis` should be plotted after background....right? For example, the axis ticks are showing up in legend.
### SEVEN.

`grid` should take major tick axis (#100)

**Comment by jordansread** [comment]
Whenever you use all caps, I get a special fear in my heart. :ghost: :heart:

**Comment by jordansread** [comment]
adding another to this humiliating thread:

EIGHT!!! logging doesn't lock on a side:

``` r
usrDef <- gsplot(mar=c(4,4,4,4), xaxs='r', yaxs='r') %>% 
    points(x=1, y=2, side=c(3,2), legend.name="Points 1", cex=3, xlab='cat',log='x') %>% 
    points(x=3:10,y=4:11, side=c(1,2), log='y')
```

![image](https://cloud.githubusercontent.com/assets/2349007/10327203/3a4713a8-6c6a-11e5-8271-b8e926883c51.png)

desired behavior is that side 2 gets logged, since that was the last call made that alters it.

**Comment by jordansread** [comment]
@ldecicco-USGS are these written in order of priority?

**Comment by jordansread** [comment]
I kind of think that the first step in print (after the set up things) should be plotting ALL the axis at once, _then_ we loop through views. This way we can enforce only unique plotting of axis

**Comment by ldecicco-USGS** [comment]
Not written in order of priority. And, I was thinking the same thing, move the draw_axis call to the first part of print. Already started in fact!

**Comment by ldecicco-USGS** [comment]
Oh....and the all caps....I wanted to just use regular numbers, but when there were code chunks in there, the gitHub's markup would restart the numbering. So it ended up like 1, 1, 1, 1, 2, 3....which seemed silly. If you know a way around this....let me know.

**Comment by ldecicco-USGS** [comment]
my brain now spells thread thredd.....
- [x] `axis` call overrides default
- [x] 2 views overplotting same axis
- [x] axis limits....I've changed my mind on this one. I don't think it should take this into account
- [ ] conflicting limits (not really in `axis`...,will probably ignore for now)
- [x] `axis` par
- [x] `axis` in background
- [ ] `grid` takes `axis` major ticks (will probably ignore for now)
- [x] log locking
- [x] axes=FALSE not making it into view window
- [x]  minor ticks need to extend to graph limits
