### ISSUE TITLE
grid + axes=FALSE + date

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#273]
```
gs <- gsplot() %>%
      points(x=seq.Date(as.Date("2000-01-01"),as.Date("2010-01-01"),length.out = 20),
             y=1:20,axes=FALSE) %>%
     grid()
gs
```

**Comment by jordansread** [comment]
@ldecicco-USGS what is wrong with this? I see 
![image](https://cloud.githubusercontent.com/assets/2349007/11602117/5a0ad808-9a9d-11e5-81fb-1346190d1b1b.png)

**Comment by jordansread** [comment]
oh, the `axes=FALSE` not being honored?

**Comment by lindsayplatt** [comment]
yeah, only for the y-axis

**Comment by jordansread** [comment]
works as expected w/ #319 PR
![image](https://cloud.githubusercontent.com/assets/2349007/14583039/a2421e04-03db-11e6-8a8f-adb2b358900e.png)
