### ISSUE TITLE
axis reverse=TRUE ignored if grid is also called

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/gsplot#274]
Works: 

```
gs <- gsplot() %>% 
  points(x=1:10, y=1:10) %>% 
  axis(side=2, reverse=TRUE)
gs
```

![rplot_reversetrue](https://cloud.githubusercontent.com/assets/6920344/10464829/49e2d15c-71b1-11e5-81f1-6827e082dfb7.png)

No worky, the axis reversal flops:

```
gs <- gsplot() %>% 
  points(x=1:10, y=1:10) %>% 
  grid(lty=3, col="gray") %>%
  axis(side=2, reverse=TRUE) 
gs
```

![rplot_reversetruegrid](https://cloud.githubusercontent.com/assets/6920344/10464839/5658856c-71b1-11e5-892b-444493ddb60d.png)

**Comment by mhines-usgs** [comment]
I've also tried to rearrange the grid call to above the axis call thinking it was an ordering issue but same problem. I haven't tried upgrading gsplot() (I'm at 0.2.3) because I think there are other issues that I would need to work out in order to see if it's still an issue. I can try that.

**Comment by mhines-usgs** [comment]
@lindsaycarr Yep, this is actually addressed with the new gsplot, I just verified by upgrading to 0.4.1 and then re running the examples. 

I'll code around it to the best of my abilities and not worry about it actually working at this point.

**Comment by jordansread** [comment]
yeah, big changes since v0.2

**Comment by ldecicco-USGS** [comment]
Actually, something is still amiss. (loses the horizontal grid)

**Comment by lindsayplatt** [comment]
It doesn't lose the horizontal grid on mine
