### ISSUE TITLE
cex in callouts goes to par

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#275]
Somehow, when `cex` is specified in callouts, it goes to `gs$view$window$par$cex` and applies to the entire graph.

``` r
gs <- gsplot() %>% 
    points(1:5, 1:5) %>% 
    callouts(3,3, labels="stuff")
gs
```

``` r
gs <- gsplot() %>% 
    points(1:5, 1:5) %>% 
    callouts(3,3, labels="stuff", cex=0.5)
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/10497996/ca93d764-728e-11e5-8767-4c52f07986b2.png)

![image](https://cloud.githubusercontent.com/assets/13220910/10498004/df50eb88-728e-11e5-9a11-31a8cdc66149.png)

**Comment by lindsayplatt** [comment]
`par=par_arguments(arguments, def.funs)` from `set_args` seems to be causing this

https://github.com/USGS-R/gsplot/blob/master/R/set_args.R#L29-L30

**Comment by ldecicco-USGS** [comment]
I can see by your sideways y labels, you need to git pull upstream master. Still an issue...just sayin'

**Comment by lindsayplatt** [comment]
I did do that right after just to make sure :)

**Comment by jordansread** [comment]
Add `cex` as a formal to callouts.default and it should fix it. Then use it in callouts for the text cex.

**Comment by lindsayplatt** [comment]
@jread-usgs that fixed it - PR coming soon
