### ISSUE TITLE
legend(location="below") does not honor "ncol" argument

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#277]
Trying to use `ncol=2` so that the legend arguments do not span past margins horizontally. Coupled with `location="below"` or `location="above"`, ncol does not seem to do anything. It works with all the other locations (toleft, toright, left, bottomleft, topleft, bottomright, etc). 

``` r
gs <- gsplot() %>% 
    points(1,2, legend.name="stuff") %>% 
    lines(1:5,1:5, legend.name="myline") %>% 
    points(10,10, legend.name="mypoints") %>% 
    abline(v=6, legend.name="vertical line") %>% 
    rect(2,2,5,3, col="green", border=NA, legend.name="myrectangle") %>%
    lines(6:8,8:6, col="purple", legend.name="another line") %>% 
    points(8,3, legend.name="another set of points") %>% 
    points(3,4, legend.name="just one more set") %>% 
    legend(location="below", ncol=2)
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/10615272/8ad9a898-7724-11e5-811a-59c30792d959.png)

``` r
gs <- gsplot() %>% 
    points(1,2, legend.name="stuff") %>% 
    lines(1:5,1:5, legend.name="myline") %>% 
    points(10,10, legend.name="mypoints") %>% 
    abline(v=6, legend.name="vertical line") %>% 
    rect(2,2,5,3, col="green", border=NA, legend.name="myrectangle") %>%
    lines(6:8,8:6, col="purple", legend.name="another line") %>% 
    points(8,3, legend.name="another set of points") %>% 
    points(3,4, legend.name="just one more set") %>% 
    legend(ncol=2)
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/10615266/7b702814-7724-11e5-9a9f-f50c67108c29.png)

**Comment by thongsav-usgs** [comment]
FYI, I think this will work fine. We had more scrict page requirements for the UV hydro previously and were trying not to push the secondary graph to the next page. I think that point is moot now.

**Comment by lindsayplatt** [comment]
It's that they are being cutoff from the width specification though - so we want to specify only 2 columns so that doesn't happen (I'll post an example in the AQCU slack)
