### ISSUE TITLE
segments.gsplot

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#28]

**Comment by jordansread** [comment]
what does this mean?

**Comment by ldecicco-USGS** [comment]
We'll want to support segments at some point. No?

**Comment by jordansread** [comment]
what is a segment?

**Comment by ldecicco-USGS** [comment]
?segments

Lines from one point to another. Useful here and there. Good for custom error bars and stuff...

**Comment by jordansread** [comment]
gotcha. Should have `?` that.
