### ISSUE TITLE
would like `x_side(window)` function that returns the x_side 

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#282]
Kind of risky to keep assuming x is always `window$side[1]`

same thing for y_side of course

**Comment by jiwalker-usgs** [comment]
Are you thinking this would be an internal function or exposed?  I'm thinking it might be a bit more generic to have a function like `sides(window)` that describes what is happening in a better way (what if there are 3 x sides?).

**Comment by ldecicco-USGS** [comment]
Check out `view_info` and `summary`. I'm not sure I showed you guys these yet:

```
demoPlot <- gsplot() %>%
  points(y=c(3,1,2), x=1:3,side=c(1,2)) %>%
  lines(10:15, 10:15, side=c(3,4) )

info <- view_info(demoPlot)
info$x[1]
1
info$x[2]
3

info$x
[1] 1 3

summary(demoPlot)
Summary information of plotting object:
2 views:
View: 1 
x side: 1 ,y side: 2 
xlim: 1 3 ,ylim: 1 3
View: 2 
x side: 3 ,y side: 4 
xlim: 10 15 ,ylim: 10 15
```

**Comment by jordansread** [comment]
Yeah, I think this is covered w/ `view_info()`
