### ISSUE TITLE
merge functionality in dinosvg w/ gsplot?

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#283]
see: https://github.com/jread-usgs/dinosvg/issues/2

wondering if that should be a package that extends `gsplot`, or if it should be part of `gsplot` since it is so heavily integrated w/ it.

**Comment by jiwalker-usgs** [comment]
My vote would be to have it extend gsplot.  There are probably going to be a good number of functions that would be svg specific, and it would just confuse gsplot users trying to do non-svg things.

**Comment by jordansread** [comment]
cool. I am thinking the same thing. Keep gsplot clean and lean.

**Comment by ldecicco-USGS** [comment]
:+1:
