### ISSUE TITLE
mtext `side=` argument is wrong

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#286]
Compare base behavior with gsplot: `mtext(..., side=1)` goes to `side=3` for gsplot

```
plot(1,2)
mtext("stuff", at=0.7, line=0, las=2, side=1)
```

![image](https://cloud.githubusercontent.com/assets/13220910/11511295/e70ca082-982d-11e5-8cda-695caafefd00.png)

```
gs <- gsplot() %>% 
    points(1,2) %>%
    mtext("stuff", at=0.7, line=0, las=2, side=1)
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/11511311/00696380-982e-11e5-8db7-624dac17a27d.png)

**Comment by lindsayplatt** [comment]
It is because the `set_window_args` function does not allow `side` to be passed in as an mtext argument. Therefore, the default for that argument is being used, which is `side=3`

**Comment by lindsayplatt** [comment]
Another issue is with specifying `las`: gsplot mtext can't have two different types or it defaults to `las=1`.

```
plot(1,2)
mtext(text=c(1,2,3,4), at=c(0.7,0.9,1.1,1.3), cex=0.5, las=2, side=1, line=1)
mtext(text=c("yr1", "yr2"), at=c(0.8, 1.2), las=1, side=1, line=3)
```

![image](https://cloud.githubusercontent.com/assets/13220910/11515660/915f29ea-9844-11e5-8b94-e3f3cd9b3e95.png)

```
gs <- gsplot() %>% 
    points(1,2) %>% 
    mtext(text=c(1,2,3,4), at=c(0.7,0.9,1.1,1.3), cex=0.5, las=2, side=1, line=1) %>% 
    mtext(text=c("yr1", "yr2"), at=c(0.8, 1.2), las=1, side=1, line=3)
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/11515693/c4eefe2a-9844-11e5-9bc8-79d0b506179a.png)

**Comment by jordansread** [comment]
@lindsaycarr going to submit a WIP PR?

**Comment by lindsayplatt** [comment]
yep, making issues for the stuff we talked about earlier

**Comment by lindsayplatt** [comment]
I was going to close this issue, but `mtext` is breaking axes. When used, axes labels are gone. Also, `las` does not seem to be working - numbers 1:4 should be turned with `las=2`

``` r
gs <- gsplot() %>% 
    points(1,2) %>% 
    mtext(text=c(1,2,3,4), at=c(0.7,0.9,1.1,1.3), cex=0.5, las=2, side=1, line=1) %>% 
    mtext(text=c("yr1", "yr2"), at=c(0.8, 1.2), las=1, side=1, line=3)
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/13227851/56ae1e36-d95e-11e5-9234-e0bfdb062299.png)

**Comment by jordansread** [comment]
in mtext.gsplot:

``` r
to.gsplot <- list(list(arguments = c(do.call(set_args, c(fun.name, user_args)), axes=FALSE),  
                         gs.config = list(legend.name = legend.name, side = side,
                                          par=par_arguments(user_args, def.funs)))) %>% 
    setNames(fun.name)
```

which is why axes would not be showing up. 

I am not sure why that is in there, do you know?

removing axes=FALSE, you get a plot w/ axes and w/o the axes warning:

![image](https://cloud.githubusercontent.com/assets/2349007/14582813/ce9a9320-03d4-11e6-8011-96e531d1ee33.png)

it still has the las issue, but the rest seems fine

**Comment by jordansread** [comment]
in mtext.R, replacing the `to.gsplot` with this:

``` r
to.gsplot <- list(list(arguments = c(do.call(set_args, c(fun.name, user_args))),
                         gs.config = list(legend.name = legend.name, side = side))) %>% 
    setNames(fun.name)
```

seems to work as expected, e.g.,

``` r
gs <- gsplot() %>% 
    points(1,2) %>% 
    mtext(text=c(1,2,3,4), at=c(0.7,0.9,1.1,1.3), cex=0.5, las=2, side=1, line=1) %>% 
    mtext(text=c("yr1", "yr2"), at=c(0.8, 1.2), las=1, side=1, line=3) %>% 
    axis(side=1,las=1) %>% 
    lines(-1:3,1:5)
gs
```

![image](https://cloud.githubusercontent.com/assets/2349007/14582919/f4790cf4-03d7-11e6-84f8-268f5ea31f9b.png)

but, it breaks the test in `mtext`:

``` r
Failed -------------------------------------------------------------------------
1. Failure: mtext on correct side (@test-mtext.R#11) ---------------------------
gs[[i]][["window"]][["axes"]] isn't false.
```

what is this testing for?

**Comment by lindsayplatt** [comment]
Could be a good additional task for @wdwatkins in the upcoming sprint.

**Comment by lindsayplatt** [comment]
related to #288

**Comment by jordansread** [comment]
noting that the default side on `mtext` is 3:

``` r
mtext.gsplot <- function(object, ..., legend.name=NULL, side = 3){

  stopifnot(length(side) == 1)
  fun.name <- 'mtext'
  object <- gather_function_info(object, fun.name, ..., legend.name=legend.name, side=side)
  return(object)
}
```

which probably explains the #288 plot being on top (even though that value should have changed...)
