### ISSUE TITLE
more par scoping necessary

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#288]
Working with mtext revealed that more par scoping is needed so that some par arguments (e.g. `las` for mtext) do not end up in the global or window par.

**Comment by jordansread** [comment]
Can you provide a simple example of this w/ code?

**Comment by lindsayplatt** [comment]
In this example, I want one of the `mtext` calls to be oriented horizontally, and one vertically. But the `las` is put in global `par`, and somehow the first `las` specified is the final value. 

``` r
gs <- gsplot() %>% 
    points(1,2) %>% 
    mtext(text=c(1,2,3,4), at=c(0.7,0.9,1.1,1.3), cex=0.5, las=2, side=1, line=1) %>% 
    mtext(text=c("yr1", "yr2"), at=c(0.8, 1.2), las=1, side=1, line=3)
gs

> gs$par$las
[1] 2
```

![image](https://cloud.githubusercontent.com/assets/13220910/14605562/be3e7c42-053e-11e6-9bf2-c2211c358fe9.png)

**Comment by jordansread** [comment]
@lindsaycarr what version are you on? this is what I see:
![image](https://cloud.githubusercontent.com/assets/2349007/16459095/3ad07982-3de7-11e6-96e2-e8d028072258.png)

(known issue w/ `box()` missing)

**Comment by lindsayplatt** [comment]
Yes, that's what I see. It's still an issue because those should be appearing at the bottom
