### ISSUE TITLE
weird axes labeling behavior

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#295]
When plotting on both y-axes, explicitly calling `axis(side=2)` results in the side=4 labels being used. The actual plot isn't changed, just what the side=2 axis is displaying for labels. Maybe @jread-usgs has an idea of where this could be coming from? 

```
#working
gs <- gsplot() %>%
    points(1:25, runif(25, 2000,5000), pch=20, col="blue") %>%
    lines(1:10, 1:10, side=4)
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/11901808/3bbd4792-a573-11e5-87cc-231434ca2202.png)

```
#not working
gsNW <- gsplot() %>%
    points(1:25, runif(25, 2000,5000), pch=20, col="blue") %>%
    lines(1:10, 1:10, side=4) %>%
    axis(side=2)
gsNW
```

![image](https://cloud.githubusercontent.com/assets/13220910/11901817/45747b16-a573-11e5-98ed-095d50e1b980.png)

**Comment by lindsayplatt** [comment]
ylim is correct, but displayed with wrong values

``` r
> ylim(gs)
$side.2
[1] 2119.038 4864.119

$side.4
[1]  1 10

> ylim(gsNW)
$side.2
[1] 2243.233 4897.816

$side.4
[1]  1 10
```

**Comment by lindsayplatt** [comment]
Having the `side=4` points put on before the `side=2` points results in the correct axis. On line 97 (https://github.com/USGS-R/gsplot/blob/master/R/axis.R#L97) of `axis.R`, it is using the correct side in params, but since most of the values are NULL, it seems to be just using params from the most recently defined side. 

``` r
gs <- gsplot() %>%
    lines(1:10, 1:10, side=4) %>%
    points(1:25, runif(25, 2000,5000), pch=20, col="blue") %>%
    axis(side=2)
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/11935385/2f66e744-a7cd-11e5-9f1a-89eb7f2b9be6.png)

**Comment by lindsayplatt** [comment]
Ok, so when `at=NULL`, the tick mark locations are calculated based off of `par("yaxp")`. The `lines(1:10,1:10)` call makes `par("yaxp") =  2 10  4` (therefore `axis(side=2)` is incorrect), and `yaxp` is between 2000 and 5000 when it is correct.

**Comment by jordansread** [comment]
Instead of creating a fix for this particular issue, can you diagnose the conceptual error that led to this issue? It would potentially lead to other similar issues.

**Comment by lindsayplatt** [comment]
the conceptual error is that we were drawing the axes outside of the views. I am about to put a pull request with a fix - I've moved drawing axes to inside of the view. And if the defined axis is not in a view, it is drawn outside of the views as was done before.

**Comment by jordansread** [comment]
ok, but see similar convo here about keeping side-specific functions outside of the view rendering. https://github.com/USGS-R/gsplot/issues/290
Thoughts on what direction this should go in?

**Comment by lindsayplatt** [comment]
Well, the only problem I foresee is that if points, lines, etc are added to the plot in `view.1.2`, but `axis(side=2)` is handled separately, anytime that `at=NULL`, it won't be using the correct 'yaxp' or 'xaxp' to calculate and you will be getting wrong labels. The axp values change everytime a new plotting feature is added. If we could somehow pass the corresponding `xaxp/yaxp` values on to when `side=__` is handled, that might work?

**Comment by ldecicco-USGS** [comment]
Putting the axis render back into the view (...having not thought about it for awhile, but thought a lot about it a few months ago) seems like a step backwards. 

It's definitely a complicated issue (specifying an axis to be drawn after both other sides have been defined). I REALLY can't work on it today, but make sure I am able to review this pull request before it gets merged. I put a lot of work into axis...and a lot of it revolves on the axis call being outside of the view.

**Comment by ldecicco-USGS** [comment]
Sorry, didn't see the latest comment, let me read that.

**Comment by lindsayplatt** [comment]
I won't merge anything anytime soon - but it's out there now, so we can discuss the best way to correct the issue I was seeing

**Comment by lindsayplatt** [comment]
(although I would like to get a robust fix sooner rather than later - this is the only thing holding up one of my tickets)

**Comment by ldecicco-USGS** [comment]
Man, I'm behind on the workflow. It's taking awhile to get use to some of the new features...but looking now.

**Comment by ldecicco-USGS** [comment]
OK, I thought you meant throwing axis back into the view part of the list. That was how we originally had it and it was a PAIN. So, just the render part is tied with view....I get it. I think it looks OK, 

As a personal favor, could you please put las: 1 in the axis part of the ymal, the default drives me absolutely bonkers, like...screen punching bonkers. Then, re-build the vignettes and readme file and see how/if the images change.

Then...I'll merge the PR. Cool?

**Comment by ldecicco-USGS** [comment]
Oh, and while you are in there...can you delete line:
https://github.com/lindsaycarr/gsplot/blob/master/R/print.R#L44

Pretty sure that was my bad.

**Comment by lindsayplatt** [comment]
So I am using https://github.com/lindsaycarr/gsplot/blob/master/R/print.R#L44 on line https://github.com/lindsaycarr/gsplot/blob/master/R/print.R#L108, but I did notice that L43-44 is a repeat of what is inside of `view_info`

**Comment by ldecicco-USGS** [comment]
Sure enough! It's like I could see into the future.

**Comment by lindsayplatt** [comment]
:crystal_ball:

**Comment by jordansread** [comment]
On #317 , this doesn't seem to be an issue:

``` r
gsNW <- gsplot() %>%
    points(1:25, runif(25, 2000,5000), pch=20, col="blue") %>%
    lines(1:10, 1:10, side=4) %>%
    axis(side=2)
gsNW
```

![image](https://cloud.githubusercontent.com/assets/2349007/14582227/afda359a-03c4-11e6-99c8-3048fd42089f.png)
