### ISSUE TITLE
bgCol should not be called automatically

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#298]
Currently, gsplot behavior is to call `bgCol` automatically (which calls `rect` within it). Therefore, when you try to remove the border around the plot, a border is still showing up. 

This should result in no border:

``` r
gs <- gsplot() %>% 
     points(1:5, 1:5, frame.plot=F, axes=F)
gs
```

BUT line 65 of bgCol has `rect(x1,y1,x2,y2,col = col,...)`. 

We have two options:
1. skip bgCol if it has not been called, OR
2. replace line 65 with `rect(x1,y1,x2,y2,col = col,..., border=NA)`

**Comment by ldecicco-USGS** [comment]
skip if not called is my vote.

**Comment by jordansread** [comment]
mine too.

**Comment by jordansread** [comment]
Just so I understand the behavior here - this happens before the other rendering functions because it needs to be behind them, right? But it should be in a `view` if it exists, right?

**Comment by lindsayplatt** [comment]
It gets the rectangle boundaries from the plot limits but it goes behind all of the other plotted features, so wouldn't it have to wait until the limits are set? As for a view, it is top-level because it is not specific to any axis

**Comment by jordansread** [comment]
yeah, I see what is going on now. I don't like that it isn't part of a view because technically, you can have views that differ in par (i.e., an inset) and you should theoretically be able to specify the bgCol of those separately, right?

**Comment by ldecicco-USGS** [comment]
I've definitely tested that inset backgrounds plot correctly...and we definitely don't want to lose that functionality.

**Comment by jiwalker-usgs** [comment]
Do insets now act as a separate window?  If so, the bgCol should be attached to the window, but should be optional.

**Comment by jordansread** [comment]
Tested as in "there are tests" or tested as in tried it out?

**Comment by lindsayplatt** [comment]
Only examples I could find on insets is from issue #14. We should think about making tests or adding an example of those into the package

**Comment by ldecicco-USGS** [comment]
Tested as in tried it out. I have my standard super-hard graphs that I run and look at the output to make sure things look right. There use to be an inset in the readme. I don't know when that got taken out, but I vaguely remember it broke and we (me?) took it out.

You're probably better at the tests than me, but it is exceptionally frustrating to test this package, because often the output in the lists stays the same (so, passes the tests), but the graph looks different. But that's a side issue.

**Comment by lindsayplatt** [comment]
@jread-usgs did this get fixed in #299 ? Not sure if we left it hanging or not

**Comment by jordansread** [comment]
not sure either. @ldecicco-USGS ?

**Comment by lindsayplatt** [comment]
we also need to not have bgCol have a border:

``` r
extra_args <- ...[-which(names(list(...)) == 'border')] 

rect(x1,y1,x2,y2,col = col, border = NA, extra_args)
```

**Comment by lindsayplatt** [comment]
is this still an issue?
