### ISSUE TITLE
create gsplot class

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#3]
decision to make S3 or S4, then implement. 

Advantage of S3 is more flexibility (and sloppiness), easier debugging, faster coding. Can do 
`points.gsplot(x,y,...)` to create the method for `points(gsplot,x,y,...)`

Advantage of S4 is more explicit code and rigidity in structure, and supports multiple arg dispatch.

**Comment by jordansread** [comment]
here is an example of `S4`: https://github.com/USGS-R/geoknife/blob/master/R/02-webgeom-obj.R
here is an example of `S3`: https://github.com/USGS-R/glmtools/blob/master/R/nml.R

**Comment by jordansread** [comment]
For completeness, R6 looks pretty sweet http://cran.r-project.org/web/packages/R6/vignettes/Introduction.html

**Comment by jordansread** [comment]
my vote is `S3`

**Comment by ldecicco-USGS** [comment]
S3

**Comment by ldecicco-USGS** [comment]
Now the issue is to implement the gsplot S3 class.

**Comment by jiwalker-usgs** [comment]
Calling this good, may need to make minor tweaks as things come up.
