### ISSUE TITLE
Cleanup builder pattern

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-R/gsplot#316]
Now that we have building of the gsplot object for each additional call, we can split out the functions that gathered all this for the render call and move to a more single responsibility pattern where functions only are concerned with sections of the gsplot object.  For example an `axis()` config might have a `gather.side()` called on it to get the xlim and ylim from the axis call and then this can be combined with the existing config for that side.

This will remove or greatly simplify the calc_views and group_views functions.

**Comment by lindsayplatt** [comment]
@jiwalker-usgs is this still relevant? calc_views doesn't exist anymore

**Comment by jiwalker-usgs** [comment]
Yeah, I think this can be closed with #320 and subsequent work
