### ISSUE TITLE
gsplot structure revisited

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#320]
Now that we have named views and sides, I would like to propose we use the concepts to structure gsplot

so top level things have their own unique print components, or are applicable to the whole object:

``` r
names(gs)
[1] "view.1.2" "side.1"   "side.2"   "par"      "legend"   "title"  
```

in the `view`s, there are things that require a "frame" to plot (e.g., points, lines, rect, etc)
in the `side`s, there are things that require knowledge of only one side (e.g., axis, mtext, etc)
in the top level `par`, these are settings that apply to the whole object
`legend` applies to the whole object too, as does `title`

`view` (note no more `window` - do we need that anymore?):

``` r
names(gs$view.1.2)
 [1] "points"   "lines"    "abline"   "grid"     "arrows"   "arrows"   "arrows"   "arrows"   "callouts"
```

`side`:

``` r
names(gs$side.1)
[1] "lim"     "log"     "label"   "usr.lim"   "axis"   "mtext"
## or geometry stuff goes into a special field:
[1] "axis"   "mtext"     "side.config"
```

potentially each of these things (view, side) would be a class? That way we could have special methods that cover the different rules of those objects, a la:

``` r
print.view(x, ...)
print.side(x, ...)
summary.view(x, ...)
summary.side(x, ...)
lim.side(x, ...)
lim.view(x, ...)
```

Thoughts? I think formalizing the structure more will help us w/ #316 and simplify other things

**Comment by jordansread** [comment]
As part of this, the `graphics::` functions that we override can be handled either as a `sides` thing or as a `views` thing. So calling `axis(1)` ends up putting defaults and an `axis` field into `side.1`. `points(1,2, side=c(1,2)` ends up in `view.1.2`.

**Comment by ldecicco-USGS** [comment]
```
names(gs)
[1] "view.1.2" "side.1"   "side.2"   "global"
```
