### ISSUE TITLE
Big picture

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#323]
- [ ] Converge on structure rules / converge on `print` workflow
- [ ] `par` scoping
- [ ] extensions?  
- [ ] Documentation of internal functions
- [ ] Vignette on internal functions
- [ ] Vignette on workflow
- [x] ~~All "special" things need to be in readme and vignettes (document sugar)~~
- [ ] Expand readme and vignettes for testing purposes
- [ ] print_script?

**Comment by ldecicco-USGS** [comment]
```
points.gsplot <- function(object, ..., legend.name=NULL, side=c(1,2)){
  fun.name <- 'points'
  call.args <- call_arguments(fun.name, ...)
  object <- add_to_view(object, call.args, side=side) # adding a point call to view
  object <- modify_side() # modify axis call
  object <- modify_legend() # modifying legend call
#If we cared about helping the user more:
  #object <- modify_title() # pull out each `main` argument and create title
  return(object)
}

mtext.gsplot <- function(object, ..., side=c(1,2)){
  fun.name <- 'mtext'
  object <- add_to_side() # adding mtext call to side
  return(object)
}

par.gsplot <- function(){
  object <- add_to_global() # or modify_par()?
}

add_to_view <- function(){
  add and modify
}

gsplot.default <- function(...) {
  object <- add_to_global()
}


```

**Comment by ldecicco-USGS** [comment]
- [x] add_to_view
- [x] modify_side
- [x] modify_legend
- [ ] add_to_side
- [ ] add_to_global

Either
- [ ] modify_global_par
- [ ] modify_view_par
- [ ] modify_side_par

Or
- [x] modify_par

**Comment by jordansread** [comment]
#333 for `add_to_view`

**Comment by lindsayplatt** [comment]
Other sugar to add:
- [ ] bgCol
- [ ] insets?
