### ISSUE TITLE
add_to_view

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#324]

**Comment by jordansread** [comment]
fixed in #333

**Comment by lindsayplatt** [comment]
`text.font` and `text.col` do not come through call_arguments, so they are not used in legend as they should be

``` r
gs <- gsplot() %>%  
    points(x=1, y=2, legend.name="Points 1", pch=1, col="blue") %>% 
    points(x=3, y=4, legend.name="Points 2", pch=5, col="red", text.font=2) %>%  
    legend()
gs
```

**Comment by lindsayplatt** [comment]
@jiwalker-usgs has an idea: legend specific args can be defined in `points` using an embedded function - like `legend_info` or something. Or look for legend specific args to add to the formals of points (like call_arguments, but not actually using call_arguments)

**Comment by jordansread** [comment]
that does sound like a good idea!
