### ISSUE TITLE
share info from function_defaults with config

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#332]
I can do this quick I think

**Comment by jordansread** [comment]
per https://github.com/USGS-R/gsplot/pull/330/files/46af52f5acc74a17fcc228accfe71343de30bf73#diff-f7297809c90a3054cda9c211f1ae9575R3

**Comment by jiwalker-usgs** [comment]
Cool, I thought this type of thing would be useful when I put it in config, but I wasn't sure what it should look like.

**Comment by jordansread** [comment]
Here is what I was thinking @jiwalker-usgs https://github.com/jread-usgs/gsplot/commit/51bb97aae50f47ab519b0a272aec56b814e1fe5e

**Comment by jordansread** [comment]
fixed in #333
