### ISSUE TITLE
modify_par

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#334]

**Comment by jordansread** [comment]
Here is my understanding of this:

The only things that modify the global par are the params that are used when creating the object, _or_ to specific calls to par.gsplot during or after building the object. 
I think everything that is captured from function calls by `gsplot:::par_arguments` right now are par settings that apply to the `view` or `side`, not to global. The other minor par things should all stay with the function calls and I think they do that now, although there are so many to understand and track.

**Comment by jordansread** [comment]
For par args that should be specific to sides:

`cex.axis, col.axis, font.axis, mgp, xaxp, yaxp, tck, tcl, las, fg, xaxt, yaxt, adj`

**Comment by jordansread** [comment]
out of those, I think `mpg`, `fg` and `adj` are the only ones that need to be "smartly" shared w/ global-par

**Comment by lindsayplatt** [comment]
Seems like this issue was fixed in the april sprint: https://github.com/USGS-R/gsplot/blob/master/R/modify_par.R. 

But are  `mpg`, `fg` and `adj` being smartly shared? Looks like only specified in `side.par` and not `global.only.par`

**Comment by jordansread** [comment]
probably not. What is your proposal?

**Comment by lindsayplatt** [comment]
I wasn't sure what you meant by "smartly" or why they needed to be shared, but couldn't you just have an additional object called `shared.par` with those three pars?
