### ISSUE TITLE
Moving on discussion

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#341]
| Function | notes |
| --- | :-- |
| ~~`append_side`~~ | replace w/  `modify_side` |
| ~~`views_with_side`~~ | nothing. Only used in `print` for checking axes right now |
| `set_args` | something more explicit for the separation of arguments |
| `function_args` | this is useful, but maybe should be renamed and def documented |
| ~~`set_inherited_args`~~ | replace with something else that deals with embedded function args |
| ~~`set_window`~~ | phase this out with `add_to_view`, `modify_side`, and `modify_par` |
| ~~`calc_views`~~ | breaking this into multiple functions |
| ~~`group_views`~~ | using `add_to_view` |
| `append_replace` | keep this as a utility function? or what? This is kind of like the mirror to `strip_pts` although not by design |
| ~~`which_reals`~~ | not used anymore. Delete |
| ~~`set_view_window`~~ | only used in `set_view_lab`, which will be replaced by `modify_side` |
| ~~`set_view_lab`~~ | replace w/ `modify_side` |
| `remove_field` | this obscures some things and we probably want some more explicit methods. Delete/replace? |
| `strip_pts` | needs to be improved if it is useful to keep |
| ~~`summarize_side_values`~~ | hopefully we can improve this or do it elsewhere |
| ~~`set_sides`~~ | confusing name, but this deals w/ turning c(1) into c(1,2) |
| ~~`non_views`~~ | we should phase this out, as our model will only contain sides, views, and global at top |
| ~~`par_arguments`~~ | deprecate? |
| `formal_arguments` | used in `call_arguments`, but should be documented and tested (if it isn't) |
| ~~`window_arguments`~~ | deprecate? |

**Comment by jiwalker-usgs** [comment]
I don't understand strip_pts, but I think it is needed within the limit calculation

**Comment by jordansread** [comment]
yes, I think `strip_pts` is kind of "extract and flatten" parts of a list

**Comment by jordansread** [comment]
updated per #342

**Comment by lindsayplatt** [comment]
Why do we have `strip_pts` and `strip_pts2`? Also, `strip_pts2` calls on itself: https://github.com/USGS-R/gsplot/blob/master/R/utils-list.R#L62

**Comment by jiwalker-usgs** [comment]
I made strip_pts2 in an attempt to replace strip_pts, though I'm not sure it covers all the use cases.  It calls itself because it is a recursive function in attempts to make it more clear (though I probably did the opposite).
