### ISSUE TITLE
Move axis into side.y and side.x

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#346]
We have discussed this, but a created side should have a default axis call when the side is created. If the user does an axis call that pertains to that side, it should overwrite the default values. Right now this is handled by putting axis in view instead of side and some funky logic in `print` to deal with it.

**Comment by jordansread** [comment]
One thing I realized with #347 is that the pattern I used w/ a single axis call per side may be limiting. 

They way that PR works, you have a template axis call by default which is only plotted if `axes==TRUE`, but additional calls to axis for the same side will just override parameter values. Is this a limitation we should avoid? It may remove some flexibility that is needed. For example, 

this 

``` r
gs <- gsplot() %>%
  points(y=c(3,1,2,4,5), x=c(1:3,8,80), 
         col="blue", pch=18, legend.name="Points") %>%
  lines(c(3,4,3), c(2,4,6), legend.name="Lines", 
        ylab="logged y axis", xlab="logged x axis", log='xy') %>%
  callouts(x=8, y=4, lwd=2, angle=45, labels="Not sure about this one") %>%
  title("logged axes") %>%
  axis(side=c(1,2,3,4), labels=FALSE, n.minor=4) %>%
  axis(side=c(1,2))
gs
```

used to produce this:
![image](https://cloud.githubusercontent.com/assets/2349007/15219448/74c07162-1829-11e6-87ec-ee5ae79403c7.png)

now you need to do 

``` r
gs <- gsplot() %>%
  points(y=c(3,1,2,4,5), x=c(1:3,8,80), 
         col="blue", pch=18, legend.name="Points") %>%
  lines(c(3,4,3), c(2,4,6), legend.name="Lines", 
        ylab="logged y axis", xlab="logged x axis", log='xy') %>%
  callouts(x=8, y=4, lwd=2, angle=45, labels="Not sure about this one") %>%
  title("logged axes") %>%
  axis(side=c(3,4), labels=FALSE, n.minor=4) %>%
  axis(side=c(1,2), n.minor=4)
gs
```

instead for this PR (note that axis is only called once per side). Otherwise, you lose the n.minor for axes 1 and 2

**Comment by lindsayplatt** [comment]
I think this is limiting, and a little confusing. I think of each axis individually, so it doesn't make sense that you can do 3,4 together but not 2,3,4.

**Comment by jordansread** [comment]
Do you have a use case? Also, note you can call all of those sides together, but there is only one `draw_axis` call executed per side. So the original code does this:

``` r
gs <- gsplot() %>%
  points(y=c(3,1,2,4,5), x=c(1:3,8,80), 
         col="blue", pch=18, legend.name="Points") %>%
  lines(c(3,4,3), c(2,4,6), legend.name="Lines", 
        ylab="logged y axis", xlab="logged x axis", log='xy') %>%
  callouts(x=8, y=4, lwd=2, angle=45, labels="Not sure about this one") %>%
  title("logged axes") %>%
  axis(side=c(1,2,3,4), labels=FALSE, n.minor=4) %>%
  axis(side=c(1,2))
gs
```

![image](https://cloud.githubusercontent.com/assets/2349007/15219783/af2807e2-182a-11e6-9549-6da9da31bcee.png)

for this new PR

**Comment by jordansread** [comment]
If n.minor didn't have a default of 0, we wouldn't override it with the second call to axis

**Comment by lindsayplatt** [comment]
Oh OK, I guess I misunderstood what you were pointing out. Thought you were saying c(1,2,3,4) was no longer allowed. So, you're saying by doing this, the new PR overrides what was specified in the first axis call. I think that makes sense. I would want this behavior

``` r
axis(side=c(1,2,3,4), labels=FALSE, n.minor=4) %>%
axis(side=c(1,2))
```

**Comment by jordansread** [comment]
Correct. So because labels = TRUE and n.minor = 0 by default, the first call to axis for sides 1 and 2 would have those values overridden by the second call.
