### ISSUE TITLE
where does box args reside (ex. frame.plot)

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#350]
@ldecicco-USGS's comment from #344 

As for framing (ie...whether or not to put a box around)...Maybe we could inject the plot.defaults at the first instance of gsplot(), and then only override them if the user does.

```
## Default S3 method:
plot(x, y = NULL, type = "p",  xlim = NULL, ylim = NULL,
     log = "", main = NULL, sub = NULL, xlab = NULL, ylab = NULL,
     ann = par("ann"), axes = TRUE, frame.plot = axes,
     panel.first = NULL, panel.last = NULL, asp = NA, ...)
```

That was my intent waaay back in the day. I can't figure out of that just got lost in the overhaul, or it's acting up.

**Comment by jordansread** [comment]
putting this in `gs$global$config$frame.plot=TRUE`

**Comment by lindsayplatt** [comment]
is that where asp and other plot.default args with no other home would live?

**Comment by jordansread** [comment]
technically, `asp` is a view thing I think, so it should be in `gs$view.1.2$config$asp` following this pattern

**Comment by jordansread** [comment]
but, Walker mentioned having the ability to bubble up those values to the global level so that they would apply across all views.
