### ISSUE TITLE
create test for reverse axis

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#352]
``` r
gs <- gsplot() %>%
   points(1:10, 1:10) %>%
   axis(1, at = seq(0,10,by=0.1),labels=FALSE, tcl=0.15) %>%
   axis(2, reverse=TRUE)
gs
```

test should hit ylim

**Comment by lindsayplatt** [comment]
In gsplot v0.5.5, `gs$view.1.2$window$ylim = 10:1` and `gs$axis$gs.config$reverse = TRUE`

But in gsplot v0.6.1, `gs$side.2$lim = 1:10` and `gs$side.2$reverse = TRUE`. The axis is shown reversed in the plot, need this reflected in the limit so we can test?

**Comment by lindsayplatt** [comment]
Oh wait, can use par('usr)[3:4] to test

**Comment by jordansread** [comment]
hmmm...would be good to dig into the part of the code that actually flips that range. Can you track it down?

**Comment by lindsayplatt** [comment]
Hunting:
- It used to happen in calc_views: https://github.com/USGS-R/gsplot/commit/33f79714db6687b6214560d10fcb0660b5cf979f
- calc_views was removed, but I can't find where this was replaced (see L194): https://github.com/USGS-R/gsplot/pull/342/files#diff-832bc7f54d2e9d5191b3bdcef9979848L194
- struggling to see how reverse=TRUE works

**Comment by jordansread** [comment]
I will take a look

**Comment by jordansread** [comment]
it is here @lindsaycarr https://github.com/USGS-R/gsplot/blob/9ff7f363ac3f17f63a7f17d52af1cc1cb738fe13/R/access-gsplot.R#L118

not sure why your `ylim` test wouldn't return the proper result though...

**Comment by jordansread** [comment]
I get this:

``` r
gs <- gsplot() %>%
    points(1:10, 1:10) %>%
    axis(1, at = seq(0,10,by=0.1),labels=FALSE, tcl=0.15) %>%
    axis(2, reverse=TRUE)
gs
```

![image](https://cloud.githubusercontent.com/assets/2349007/16463168/2ed947ea-3dfa-11e6-95e5-19fa517ada9b.png)

``` r
ylim(gs)
$side.2
[1] 10  1
```

**Comment by jordansread** [comment]
oh, I see above - you are accessing the ylim directly, instead of using the accessor methods
"But in gsplot v0.6.1, gs$side.2$lim = 1:10"
should use 
`ylim(gs, 2)`

**Comment by lindsayplatt** [comment]
Haha oh my gosh...cannot believe I did not try that at all. I always forget about those helper functions

**Comment by lindsayplatt** [comment]
While adding tests, I figured out that reverse=TRUE for axis > 2 is not working. See #356
