### ISSUE TITLE
custom legend is broken

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#353]
@jiwalker-usgs worked on this and got it working, but then you couldn't add multiple legends

``` r
gsplot() %>%
 points(1:4, 1:4, col=c("red","black","blue","green"), cex=1:4, pch=15:18) %>%
 legend(location = "topleft", pch=15:18,
       legend=c("a","b","c","d"),col="red", title = "Shape" ) 
```

**Comment by lindsayplatt** [comment]
Do not allow auto-legends + multiple legends. If someone wants multiple legends they should make multiple user-specified legends, and not the auto (`legend.name`). If someone tries to mix the two, throw a warning (as in someone specifies `legend.name` and then multiple `legend` calls).

**Comment by lindsayplatt** [comment]
Currently, `legend.name` is what determines whether auto-legend is used or not. @jread-usgs suggests using `auto.legend=FALSE` to trigger that. Then, people can still specify `legend.name` without the auto legend being drawn. Makes it more explicit

**Comment by lindsayplatt** [comment]
Should we have a separate function called `autoLegend` or something similar? Then we can mix auto + multiple?

**Comment by lindsayplatt** [comment]
For 2 custom legends and one legend using `legend.names`:

gs$legend$legend.auto
gs$legend$legend.1
gs$legend$legend.2

When first legend.name is specified, legend.args and gs.config are added to legend$legend.auto (instead of those sublists). 

If I call `legend()` with no argument `legend=`, then it will update gs$legend$legend.auto$draw to be TRUE.

**Comment by jordansread** [comment]
@jiwalker-usgs I touched a few things in `legend` for #365 . Hopefully they don't get in the way.

**Comment by jiwalker-usgs** [comment]
Should be fine, thanks @jread-usgs
