### ISSUE TITLE
non-pars that are global should elevate to gsplot()

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#366]
e.g. frame.plot, asp

``` r
gs <- gsplot(frame.plot=FALSE)
#instead of 
gs <- gsplot() %>% points(1,1,frame.plot=FALSE)
```

**Comment by lindsayplatt** [comment]
@jread-usgs 

global.par
global.config
view.par
view.config

or instead it gets funneled to the function that actually uses it (@jiwalker-usgs)
- [ ] ~asp goes to plot.window()~ see #367 
- [x] frame.plot goes to box()

**Comment by lindsayplatt** [comment]
add frame.plot to global.only.par in modify_par.R

**Comment by lindsayplatt** [comment]
@ldecicco-USGS get list (7 args) and cross ref to what's in global now

**Comment by lindsayplatt** [comment]
`asp` is tricky - try to get it to match base

**Comment by ldecicco-USGS** [comment]
https://svn.r-project.org/R/trunk/src/library/graphics/R/plot.R

```
plot.default <-
    function(x, y = NULL, type = "p", xlim = NULL, ylim = NULL,
             log = "", main = NULL, sub = NULL, xlab = NULL, ylab = NULL,
             ann = par("ann"), axes = TRUE, frame.plot = axes,
             panel.first = NULL, panel.last = NULL, asp = NA, ...)
```

So....`axes`, `frame.plot`, `panel.first`,`panel.last`, and `asp`?

**Comment by ldecicco-USGS** [comment]
main
sub
~axes~ works within `view()`
~asp?~ see #367 dealing with this at a later date
~xlab~ needs to be called within a side call
~ylab~ needs to be called within a side call

**Comment by lindsayplatt** [comment]
asp needs to affect the view

**Comment by jordansread** [comment]
I think ylab and clan should stay on sides, right?

**Comment by jordansread** [comment]
Autocorrect! xlab

**Comment by ldecicco-USGS** [comment]
I think we're talking about 2 different things. Yes, ylab and clan :)  should go to sides. But, I was listing the things that should be allowed/accounted for when initiating the gsplot object. ie... the arguments that are in plot.default.
