### ISSUE TITLE
gsplot testing w/ repgen

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#375]
@lindsaycarr is working on:
- [x] ~~sensorreading~~ [doesn't use gsplot]
- [x] ~~sitevisitpeak~~ [doesn't use gsplot]
- [x] uvhydrograph
- [x] vdiagram

@mhines-usgs is working on:
- [x] correctionsataglance
- [x] dvhydrograph
- [x] ~~extremes~~ [doesn't use gsplot]
- [x] fiveyeargwsum

**Comment by lindsayplatt** [comment]
vdiagram:

| gsplot v0.5.5 | gsplot v0.6.9 |
| :-: | :-: |
| ![image](https://cloud.githubusercontent.com/assets/13220910/16591537/00ef0430-42a2-11e6-8295-5a07b95522e4.png) | ![image](https://cloud.githubusercontent.com/assets/13220910/16591552/11e2ce98-42a2-11e6-8dae-a44753d7b58d.png) |

**Comment by lindsayplatt** [comment]
issues with many of the plots: `Error in as.Date.numeric(value) : 'origin' must be supplied`

Happens because we setup limits of the plot using a lines call with NAs, but the date format is not retained in `side.1$lims`. Is there a better way for users to set up limits of the plot before adding any data?

``` r
x <- seq(as.Date("2010-10-01"), as.Date("2010-10-31"), by="days")
y <- 1:31

test_gs <- gsplot() %>% 
  lines(as.POSIXct(NA), as.numeric(NA), xlim=c(min(x), max(x)),
        ylim=c(min(y), max(y)))
test_gs <- test_gs %>% lines(x,y)
```

**Comment by mhines-usgs** [comment]
Thanks for elegantly describing this problem! The best I came up with is that whenever dates are used in the data.range in set_side_lim, they currently don't contain the proper format?

**Comment by lindsayplatt** [comment]
More specifically, this line is changing the Date format to numeric: https://github.com/USGS-R/gsplot/blob/master/R/utils-side.R#L131

**Comment by mhines-usgs** [comment]
corrections at a glance, dvhydro and fiveyeargwsum all have the origin issue.

**Comment by lindsayplatt** [comment]
@mhines-usgs try checking out my gsplot branch to get passed that `'origin' must be supplied` error: https://github.com/USGS-R/gsplot/pull/376

**Comment by lindsayplatt** [comment]
`legend.name` is no longer in the final gsplot object features - so our repgen function `reorderPlot` no longer works. How can we address this? We have discussed that feature being in gsplot here https://github.com/USGS-R/gsplot/issues/207

https://github.com/USGS-R/repgen/blob/master/R/utils-shared.R#L57-L79

**Comment by jordansread** [comment]
what does reorder do for you? Is it some ordering that can be exposed through #207 instead?

**Comment by lindsayplatt** [comment]
Yes, put that in my comment :+1:

**Comment by mhines-usgs** [comment]
After pulling your branch I see that we will need to add yaml to repgen's DESCRIPTION when attempting to make a report now. Put this here and will keep going -> https://github.com/USGS-R/repgen/issues/365

**Comment by mhines-usgs** [comment]
We can get by the origin issue above with Lindsay's temporary fix, resolve the yaml issue easily, but then lazy_dots rears its head for dvhydro, 5yeargwsum and corrections at a glance.

**Comment by mhines-usgs** [comment]
@lindsaycarr going back to old lazy eval version, those three plots work.

**Comment by jordansread** [comment]
so there is an issue with lazy eval > v.X?

**Comment by lindsayplatt** [comment]
uvhydrograph is rendering, but missing axes ticks and labels on the primary plot (but has them on the secondary plot). It's also missing the legend, and secondary plot approval line is appearing in the wrong location. The vertical gridlines (secondary plot) also look a little strange. This is using first example in [sig-uvhydrograph.R](https://github.com/USGS-R/repgen/blob/master/R/sig-uvhydrograph.R#L12-L13)

![image](https://cloud.githubusercontent.com/assets/13220910/16601316/65704d86-42d1-11e6-9c56-c32cfc313401.png)

**Comment by jordansread** [comment]
@lindsaycarr are these done w/ layout or something else?

**Comment by lindsayplatt** [comment]
Each plot is printing out in an Rmarkdown document

**Comment by jordansread** [comment]
hmmm...so no real reason why plot one wouldn't have ticks?

**Comment by lindsayplatt** [comment]
they are two separate functions, so there could easily be a difference.

**Comment by lindsayplatt** [comment]
See repgen PR that is implementing the new gsplot changes: https://github.com/USGS-R/repgen/pull/371

still need to investigate:
- funky gridlines in fiveyrgwsum (sig-fiveyrgwsum.R example)
- missing legends in dvhydro (sig-dvhydrograph.R example)

![image](https://cloud.githubusercontent.com/assets/13220910/16634915/f1ef2dfa-439d-11e6-9b12-a58456dcd3c8.png)

![image](https://cloud.githubusercontent.com/assets/13220910/16634953/19a94ab0-439e-11e6-88a1-8a909834f404.png)

**Comment by mhines-usgs** [comment]
@lindsaycarr I can continue looking at dvhydro, I have been trying to figure out the legend disappearance on and off today but getting distracted.

**Comment by lindsayplatt** [comment]
Lindsay is working on these before this task can be marked done:

corr
    - ~~duplicated legend items using example5~~
dvhydro
    - ~~aqcu744_newData + waterlevel-example has error (gs not found)~~
    - ~~yaxis label is covered by axis values (example + estimated-20131110thru20131210)~~
uvhydro
    - ~~missingmonth is cutting off error bars~~
