### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#385]
``` r
gs <- gsplot(theme="hadley") %>%
      points(1:10, 1:10, legend.name="cool")
```

the theme will pre-set things like axis, grid, bgCol etc, and call a new config.yaml.

**Comment by jordansread** [comment]
can't wait to try this one out!

**Comment by lindsayplatt** [comment]
Forcing certain gsplot calls:
- legend
- all 4 axes
- fonts

Have some themes available 
Allow users to make their own theme

Combination of gsplot object & config
But start with just a gsplot object w/ class
Later on we can add more unique ability 

Theme can call a config file (theme contains config)
Specify theme, then a config. A user config should override a theme's config (not auto config)

**Comment by ldecicco-USGS** [comment]
need to change the themes to background_color (currently still bgCol). Also, seems like there's a new issue with grid + background_color. I'll try to take care of while confirming this issues is good.

**Comment by lindsayplatt** [comment]
what PR closed this?

**Comment by ldecicco-USGS** [comment]
#435
