### ISSUE TITLE
lost date formatting/handling

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#395]
dates are coerced to numeric now
- [ ] POSIXct
- [ ] Date
- [ ] test for POSIXct
- [ ] test for Date

``` r
some_dates <- seq(as.POSIXct("2010-10-01"), as.POSIXct("2011-09-30"), by="month")
gs <- gsplot() %>% 
  points(some_dates, 1:12)
gs
```

![image](https://cloud.githubusercontent.com/assets/13220910/16740084/6ef270a2-476b-11e6-9dd7-21148040c24b.png)

**Comment by jordansread** [comment]
weird part is that `xlim` is correct:

``` r
xlim(gs)
$side.1
[1] "2010-10-01 CDT" "2011-09-01 CDT"
```

is the bug in `draw_axis`?

**Comment by jordansread** [comment]
Note what `draw_custom_grid` does, which draw_axis does not do (see #343 ?)

``` r
if(is.numeric(lim)){
    at <- axTicks(side)
  } else{
    fun <- getFromNamespace(paste0('axis.',class(lim)[1L]),'graphics')
    at <- fun(side, x = lim, lwd=0, lwd.ticks=0, labels = FALSE)
  }
```

but that is for `at`, not for the label

**Comment by lindsayplatt** [comment]
see #396
