### ISSUE TITLE
fix issue with calls to lines and points where you need to specify x= and y=

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#42]
can't do:

``` R
points(gs, 1:5, 1:5) 
```

want to

**Comment by jiwalker-usgs** [comment]
#50 should fix this, not the prettiest and has some manual copying that might cause headaches later

**Comment by jordansread** [comment]
probably get a test in there that calls the examples in `graphics::points,lines`? worth it?

**Comment by jiwalker-usgs** [comment]
yeah, examples should probably do gsplot and base graphics calls to illustrate how awesome everything is.

**Comment by jordansread** [comment]
I will create a test and then close this issue

**Comment by jordansread** [comment]
``` R
plot(-4:4, -4:4, type = "n")  # setting up coord. system
  points(rnorm(200), rnorm(200), col = "red")
```

``` barf
 Error in plot.xy(xy.coords(x, y), type = type, ...) : invalid plot type 
```

**Comment by ldecicco-USGS** [comment]
So what is this test trying to show? Once you've put type="n"....I'd want an error when calling `points`

Plus, that's all `plot.xy`, right?

**Comment by ldecicco-USGS** [comment]
I'd like tests, examples, and a kick-ass vignette too by the way
