### ISSUE TITLE
Add axis.Date & Posic & others? to our "formals" list

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#423]

**Comment by ldecicco-USGS** [comment]
Didn't we get rid of the actual list of functions we support?

**Comment by lindsayplatt** [comment]
Hmm we might have. I know we were trying to move away from having that hard-coded. @jiwalker-usgs @jread-usgs

**Comment by ldecicco-USGS** [comment]
Oh, it's `.onAttach` in gsplot.R

**Comment by lindsayplatt** [comment]
`axis` call loses `format`
