### ISSUE TITLE
ylab / xlab needed

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#43]

**Comment by ldecicco-USGS** [comment]
using the `title` function internally

**Comment by ldecicco-USGS** [comment]
Nope, `mtext`

**Comment by jordansread** [comment]
@ldecicco-USGS and others: What does this look like in the workflow? 

``` R
gsNew <- points(gsplot(list()), c(3,4,3), c(2,4,6), ylim=c(0,10), ylab='pizza cost ($/za)')
gsNew
```

**Comment by jordansread** [comment]
I can elevate this up in `views`, but something needs to do something with it.

**Comment by ldecicco-USGS** [comment]
Yeah, we need to add mtext to print. Is that what you are asking?

**Comment by jordansread** [comment]
just wondering how to divide the work here

**Comment by ldecicco-USGS** [comment]
I'm heading out 'for lunch' (exercise), so feel free to tackle it if you want.

**Comment by jordansread** [comment]
ok, I will do the views part and then assume we are going to have a labels function that will be able to handle things
