### ISSUE TITLE
Rethink error_bar arguments

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#433]
"y.low seems like it's the low value for y, ie: the actual value where you place the low bar. i suppose you could keep y.low to mean that, and add another param if someone wanted to specify the error up/down (offsets)."

**Comment by lindsayplatt** [comment]
This is an easy fix if we do anything about it, so I am pulling it in. I think it needs to be done sooner rather than later, otherwise we just continue as we have it currently implemented. Let's discuss.

**Comment by jordansread** [comment]
Changing it now also makes it easier to add as an additional parameter that gets included in the limit calculation as mentioned in #442. If we keep as-is, we kind of need to transform/calculate the argument into something else to use it.

**Comment by lindsayplatt** [comment]
New arg names: 

offsets:
offset.up
offset.down
offset.left
offset.right

Change arg names to the offset versions.
