### ISSUE TITLE
log (and others?) need to be inherited to side 3,4 for axis

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#444]
```
gsplot() %>%
   points(1:100, 1:100, log="xy") %>%
   axis(side=c(3,4)) 
```

**Comment by lindsayplatt** [comment]
I think this is working now. @ldecicco-USGS please verify.

```r
gsplot() %>%
   points(1:100, 1:100, log="xy") %>%
   axis(side=c(3,4)) 
```

![image](https://cloud.githubusercontent.com/assets/13220910/24115222/a6f29736-0d70-11e7-8fcc-4f0b29dce7de.png)

**Comment by lindsayplatt** [comment]
Might not actually be done.

**Comment by ldecicco-USGS** [comment]
The opposite of this issue seems to be still in gsplot. I'll close this and make a new issue.
