### ISSUE TITLE
User defined xlim,ylim

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#47]
`ylim = c(NA,2)`
 `log`
`main`
`ylab`
etc

**Comment by ldecicco-USGS** [comment]
Formals of plot.default but not plot.xy

**Comment by ldecicco-USGS** [comment]
Need to go in gsConfig

**Comment by jordansread** [comment]
The way I am doing this doesn't plop them into gs.config. PR coming.
