### ISSUE TITLE
calc_views sensitive to any items in gsplot with an "arguments" or "gs.config" attribute.

### ISSUE THREAD

**Issue by thongsav-usgs** [USGS-R/gsplot#54]
calc_views keys off points$arguments, points$gs.config, lines$arguments, and lines$gs.config.

I attempted to structure the legend data into legend$arguments and legend$gs.config. This resulted in calc_views throwing errors. Changing to legend$legend.arguments and legend$legend.gs.config got around the problem, but calc_views should probably be updated to avoid that sensitivity (by being more explicit in pulling point/line attributes).

**Comment by ldecicco-USGS** [comment]
So just to double check with you guys....

arguments = any argument normally sent to a base function

gs.config = arguments special to gsplot

**Comment by thongsav-usgs** [comment]
I believe so. That was how I was interpreting it, I made the change so that I could blindly forward arguments through to the base legend call.

**Comment by ldecicco-USGS** [comment]
I'm about to go rogue and move creating the gs.config sublist to overrideGraphics since I think all the things that we will be overriding will want to do that. Holler if you think that's a bad idea.

**Comment by jordansread** [comment]
@thongsav-usgs this should be fixed now, and I modified your `legend` functions to get them back to `arguments` and `gs.config`
