### ISSUE TITLE
smart legend method

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#6]
This will track inputs of appended objects and make them available for adding a legend to plot

**Comment by jordansread** [comment]
if everything is the same w/ two things, create just one addition to the legend

**Comment by jordansread** [comment]
`legend.name` is an arg added to `points.gsplot()`. If this is missing/NULL what do we do?

**Comment by thongsav-usgs** [comment]
@jread-usgs and @ldecicco-USGS, should we close this ticket? All comments in this ticket are covered in https://github.com/USGS-R/gsplot/pull/56

**Comment by ldecicco-USGS** [comment]
sure
