### ISSUE TITLE
Null legend

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#65]
Need a way to specify that a data set (line, points, abline) doesn't show up in the legend. For example, maybe a user want's to put a 1:1 line and not have it show up in the legend. So:

``` r
gsNew <- gsplot(list())
gsNew <- points(gsNew, y=1, x=2, col="blue", pch=18, legend.name="Points")
gsNew <- lines(gsNew, c(3,4,3), c(2,4,6),legend.name="Lines")
gsNew <- abline(gsNew, v=3, lty=1,legend.name=NULL)
gsNew
```

Currently the default is "Plotted Line"...do we want that to be the default, and specifying NULL to drop that legend info? Or, default means no legend (for that data set)?

**Comment by jordansread** [comment]
hopefully we just don't give it a legend.name?

**Comment by jordansread** [comment]
yeah, or your NULL. Didn't see that

**Comment by ldecicco-USGS** [comment]
I'm leaning towards setting the default to NULL, which then tells gsplot don't put this data in the legend (that is, when you don't specify a legend.name, nothing shows up for that data set).

**Comment by jordansread** [comment]
I agree. good idea
