### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#71]
Support

**Comment by jordansread** [comment]
highest priority :100:

**Comment by jordansread** [comment]
Am working on this on a logged_axis branch. Challenging because we need to also reset the `xaxp` or `yaxp` if y or x is logged.

**Comment by jordansread** [comment]
``` R
gs <- gsplot() %>%
    lines(c(1,3,4,20),c(1,2,3,4),log='x')
gs
```

![image](https://cloud.githubusercontent.com/assets/2349007/8641645/6b0157da-28de-11e5-965d-1e8244aba89e.png)

but I am hardcoding the `xaxp` reset manually right now until I can figure it out.
