### ISSUE TITLE
update README.md with working examples

### ISSUE THREAD

**Issue by jordansread** [USGS-R/gsplot#74]
that was our old ideas and is now outdated

**Comment by jordansread** [comment]
:+1: :100:

**Comment by ldecicco-USGS** [comment]
While I wait for the insanely long as-cran checks on dataRetrieval....

Could someone see if they can 'Knit' the README.Rmd and get an image that isn't corrupted somehow? I'm curious to know if it's a problem on my end or somewhere else. On my computer, the png image is just fine....but when I push it to gitHub, it doesn't work.
