### ISSUE TITLE
Smart xlab, ylab

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#78]
If side=3 or 4, doesn't seem to work now.

**Comment by jordansread** [comment]
works with xlab on side 3, 
![image](https://cloud.githubusercontent.com/assets/2349007/8489488/6ff5837e-20e1-11e5-8b59-2d3f02442823.png)
just clips the y on side 4 because of the margins.

**Comment by jordansread** [comment]
if you change par()$mar from c(5.1,4.1,4.1,2.1) to c(4.1,4.1,4.1,4.1), the right side doesn't get clipped:
![image](https://cloud.githubusercontent.com/assets/2349007/8709042/52dabce0-2b05-11e5-9f72-8e0429d5911b.png)
