### ISSUE TITLE
All of our help files are not helpful

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#80]

**Comment by jordansread** [comment]
@lindsaycarr can you help populate the documentation in the package?

**Comment by lindsayplatt** [comment]
@jread-usgs I can do that - might be a bit slow because I am still trying to understand what each function does.

**Comment by lindsayplatt** [comment]
@jread-usgs I am confused about documentation for the functions that also have a default function (e.g. callouts)

**Comment by jordansread** [comment]
@lindsaycarr want to skip those for the time being?

**Comment by lindsayplatt** [comment]
@jread-usgs okay

**Comment by ldecicco-USGS** [comment]
Closing the issue because it's a lot better now. But of course, we should always make them more helpful.
