### ISSUE TITLE
Take into account arrows for xylim calculations

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/gsplot#87]

**Comment by jordansread** [comment]
``` R
gs<- gsplot() %>% arrows(1,1,2,3) %>% points(1,1)
gs
```

**Comment by jordansread** [comment]
does this:
![image](https://cloud.githubusercontent.com/assets/2349007/8581715/214a44fc-2588-11e5-8409-15648e98db61.png)
 we want it to do this:
![image](https://cloud.githubusercontent.com/assets/2349007/8581749/4cf29a46-2588-11e5-8249-46dd261815b0.png)

**Comment by ldecicco-USGS** [comment]
I think change:
https://github.com/USGS-R/gsplot/blob/master/R/calc_views.R#L114

to something like:

``` r
xData <- do.call(c, unname(dataViews[ which(names(dataViews) %in% c("x","x1","x2")]))
```

and the same for y here:
https://github.com/USGS-R/gsplot/blob/master/R/calc_views.R#L92

**Comment by ldecicco-USGS** [comment]
(UNTESTED!)
