### ISSUE TITLE
par()$usr[1:2] is not honored on return after the print method

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/gsplot#88]

**Comment by jordansread** [comment]
I think this is because we reset par after we exit the print method.

**Comment by ldecicco-USGS** [comment]
Yeah, so do we really want to do that? If we reset, the user can't add stuff manually later (ie..with base R). If we don't reset, the altered par's stay in the system...but I don't think that's a big deal.

**Comment by ldecicco-USGS** [comment]
OH, and that fixes our mfcol problem!

**Comment by ldecicco-USGS** [comment]
OK, so in PR #140, I did this in print:

``` r
# par(defaultPar)
```

(commented it out)...
For something like the inset plot, the user will have to know to reset the par...but they would in base R too. But, I think there are far more benefits than drawbacks to not reseting par.

However, maybe there are other issues I'm missing...hence I'll keep this open for awhile.

**Comment by ldecicco-USGS** [comment]
And now:

``` r
par(mfcol=c(2,2))
for(i in 1:num.plots){
  gs<-gsplot() %>%
    points(i,2) 
  print(gs)
}
```

![test](https://cloud.githubusercontent.com/assets/1105215/8828375/7877c3ba-3057-11e5-8df6-f30d2bfa6739.png)
