### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#94]
I've always wanted a easy way to background color option to do something like this:

![2015-07-09_17-14-41](https://cloud.githubusercontent.com/assets/1105215/8608176/212c5902-265e-11e5-8953-1b91c5e24d0d.png)

**Comment by ldecicco-USGS** [comment]
Workflow might be something like:

``` r
gs <- gsplot()%>%
  points(1,1) %>%
  bg("red")
gs
```

Base R is:

``` r
plot(1,1)
rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col = "red")
par(new=TRUE)
plot(1,1)
```

**Comment by lindsayplatt** [comment]
There's a function within ggplot2 that is called "panel.background" - it might be what you are looking for. This is the example I came up with:

``` r
df <- as.data.frame(cbind(c(1,1), c(2,2)))
p <- ggplot(df) + 
  geom_point(aes(x=df[,1], y=df[,2])) +
  theme(panel.background = element_rect(fill="red"))
p
```

**Comment by ldecicco-USGS** [comment]
Yup, that's exactly the idea. We're not using ggplot2 however, so we need to make our own function.

**Comment by ldecicco-USGS** [comment]
FYI, we're going supporting geom_point either (at least for now...I think that would be entirely too confusing for both users and developers to support both base R and ggplot2 functions)

**Comment by lindsayplatt** [comment]
Right, ok not really sure where to start to create the function that fits in to the gsplot package...I know how to set up basic functions, but not sure about functions within a package

**Comment by ldecicco-USGS** [comment]
It's not trivial. Have a look at the error_bars functions:

https://github.com/USGS-R/gsplot/blob/master/R/error_bars.R

I'm a little busy right this sec, but see if you can figure out what's going on there. It would be the same idea to add a function bgCol or something like that.

**Comment by lindsayplatt** [comment]
Yeah, no worries. I'll see what I can crankout

**Comment by ldecicco-USGS** [comment]
:+1:

**Comment by lindsayplatt** [comment]
So I am not sure exactly how to set up this function to work with the rest of gsplot because I don't really understand how all of the functions in the package work together yet. I used something from a package called "RColorBrewer" for now to generate a list of colors in a gradient, but can remove that if the idea is to minimize the number of other packages used. 

Here is a function using RColorBrewer and base plot features: 

``` r
bgCol <- function(object, palette, num.plots, ncol, nrow, ...) {
  if (num.plots > 1) { 
    plotmatrix <- matrix(seq(1:num.plots), ncol, nrow) 
  }
  else {plotmatrix <- c(1)
  }

  library(RColorBrewer)
  colors <- brewer.pal(length(plotmatrix), palette) #list of x colors in the specified palette ("object")
  layout(plotmatrix)
  for (i in 1:num.plots) {
    plot.new()
    rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col = colors[i])
    par(new=TRUE)
    plot(object[,1], object[,i+1], xlab=colnames(object)[1], ylab=colnames(object)[i])
  }
}

#example
bgCol(quakes, "Reds", num.plots=4, ncol=2, nrow=2)
```

Still a big work in progress, especially with getting it to mesh with gsplot, but I wanted to share progress thus far.

**Comment by jiwalker-usgs** [comment]
I think pulling in RColorBrewer makes sense.  The goal of minimizing other packages used is mostly for maintainability, and bringing in packages willy-nilly is discouraged.  This has a very solid reason for bringing it in and the functionality fits with the overall goal of this package.

**Comment by jordansread** [comment]
and 508 compliance reasons: http://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-section-508-standards

**Comment by jordansread** [comment]
nice work @lindsaycarr !

**Comment by ldecicco-USGS** [comment]
I'd pull just the `rect` bits out to make one function for this package. My view is also to leave (for now...maybe there'd be a reason to add it in the future) RColorBrewer out too....

I'll submit a pull request pretty soon because I can't help myself to show you what I mean. Then the rest of the script you got up there would still work.

**Comment by ldecicco-USGS** [comment]
(I probably caused some confusion with the name bgCol....that to me was standing for background color...not background + columns)....

**Comment by ldecicco-USGS** [comment]
OK, so that's what I'm thinking. I was going to then show that you can still do @lindsaycarr 's matrix like this:

``` r
library(RColorBrewer)
num.plots <- 4
ncol <- 2
nrow <- 2
plotmatrix <- matrix(seq(1:num.plots), ncol, nrow) 
colors <- brewer.pal(length(plotmatrix), "Reds")
layout(plotmatrix)
for(i in 1:num.plots){
  gs<-gsplot() %>%
    points(i,2) %>%
    bgCol(colors[i])
  gs
}
```

BUT...we need some sort of print function inside of a loop....that's a new issue

**Comment by lindsayplatt** [comment]
I tried to get it to print all 4 plots onto one figure for awhile yesterday, and found that using "split.screen" works better with the loop. You do need to use "print(gs)" within the loop as @jread-usgs suggested in #99

``` r
  library(RColorBrewer)
  num.plots <- 4
  ncol <- 2
  nrow <- 2
  colors <- brewer.pal(num.plots, "Reds")
  split.screen(figs = c(nrow, ncol))
  for(i in 1:num.plots){
    screen(i)
     gs <- gsplot() %>%
      points(i,2) %>%
      bgCol(colors[i]) 
     print(gs)
  }
```

**Comment by jordansread** [comment]
great work @lindsaycarr 

not sure why layout wouldn't work. Any idea? I think I see the same thing as you, which is one plot in the upper left when using layout instead of split.screen

**Comment by lindsayplatt** [comment]
That's what was happening with mine as well - I'm not exactly sure what is happening, but I know split.screen and layout both set up the plotting area, but with split.screen we can use screen(i) to specify where the current plot will go.
