### ISSUE TITLE
Show? modify print? for loop

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/gsplot#99]
Can't do a loop of plops

``` r
num.plots <- 4
for(i in 1:num.plots){
  gs<-gsplot() %>%
    points(i,2) 
  gs
}
```

Most of these kinds of things would make you wrap gs in `print`, but we're already using that function. Maybe we need to make a new print-esque function?

**Comment by jordansread** [comment]
it does work if you just wrap w/ print

``` R
num.plots <- 4
for(i in 1:num.plots){
  gs<-gsplot() %>%
    points(i,2) 
  print(gs)
}
```

but it would be nice to do it automagically w/o the user needing to know they need to wrap `gs` w/ `print()`
hadley doesn't seem to have special magic on this, but maybe that is elsewhere?
https://github.com/hadley/ggplot2/blob/master/R/plot-render.r#L179

**Comment by jordansread** [comment]
closing this since gsplot is the same as ggplot for this behavior: http://stackoverflow.com/questions/15678261/r-ggplot-does-not-work-if-it-is-inside-a-for-loop-although-it-works-outside-of

**Comment by ldecicco-USGS** [comment]
Huh, I thought I tried `print` when I wrote it.

**Comment by jordansread** [comment]
re-open if that doesn't work - it should.
